### ISSUE TITLE
An error occurred while closing the server

### ISSUE THREAD

**Issue by flandretw** [bergerhealer/BKCommonLib#104]
##### Spigot version:Paper-379 (MC: 1.15.2)

<hr>

#### Problem or bug:
```
[23:34:21] [Server-Worker-2/ERROR]: Caught exception in thread Thread[Server-Worker-2,4,main]
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:534) ~[patched_1.15.2.jar:git-Paper-379]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:212) ~[patched_1.15.2.jar:git-Paper-379]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:197) ~[patched_1.15.2.jar:git-Paper-379]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:192) ~[patched_1.15.2.jar:git-Paper-379]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:156) ~[patched_1.15.2.jar:git-Paper-379]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:125) ~[patched_1.15.2.jar:git-Paper-379]
	at com.bergerkiller.bukkit.common.internal.CommonNextTickExecutor.executeFallback(CommonNextTickExecutor.java:111) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonNextTickExecutor.execute(CommonNextTickExecutor.java:80) ~[?:?]
	at com.bergerkiller.bukkit.common.utils.CommonUtil.nextTick(CommonUtil.java:601) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.logic.LightingHandler_1_14.lambda$scheduleSetLayerStorageData$3(LightingHandler_1_14.java:238) ~[?:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_261]
	at net.minecraft.server.v1_15_R1.LightEngineThreaded.b(LightEngineThreaded.java:291) ~[patched_1.15.2.jar:git-Paper-379]
	at net.minecraft.server.v1_15_R1.LightEngineThreaded.lambda$queueUpdate$24(LightEngineThreaded.java:276) ~[patched_1.15.2.jar:git-Paper-379]
	at net.minecraft.server.v1_15_R1.ThreadedMailbox.e(ThreadedMailbox.java:78) ~[patched_1.15.2.jar:git-Paper-379]
	at net.minecraft.server.v1_15_R1.ThreadedMailbox.a(ThreadedMailbox.java:121) ~[patched_1.15.2.jar:git-Paper-379]
	at net.minecraft.server.v1_15_R1.ThreadedMailbox.run(ThreadedMailbox.java:86) ~[patched_1.15.2.jar:git-Paper-379]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_261]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
[23:34:21] [Server-Worker-3/ERROR]: Caught exception in thread Thread[Server-Worker-3,4,main]
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:534) ~[patched_1.15.2.jar:git-Paper-379]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:212) ~[patched_1.15.2.jar:git-Paper-379]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:197) ~[patched_1.15.2.jar:git-Paper-379]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:192) ~[patched_1.15.2.jar:git-Paper-379]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:156) ~[patched_1.15.2.jar:git-Paper-379]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:125) ~[patched_1.15.2.jar:git-Paper-379]
	at com.bergerkiller.bukkit.common.internal.CommonNextTickExecutor.executeFallback(CommonNextTickExecutor.java:111) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonNextTickExecutor.execute(CommonNextTickExecutor.java:80) ~[?:?]
	at com.bergerkiller.bukkit.common.utils.CommonUtil.nextTick(CommonUtil.java:601) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.logic.LightingHandler_1_14.lambda$scheduleSetLayerStorageData$3(LightingHandler_1_14.java:238) ~[?:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_261]
	at net.minecraft.server.v1_15_R1.LightEngineThreaded.b(LightEngineThreaded.java:291) ~[patched_1.15.2.jar:git-Paper-379]
	at net.minecraft.server.v1_15_R1.LightEngineThreaded.lambda$a$14(LightEngineThreaded.java:209) ~[patched_1.15.2.jar:git-Paper-379]
	at net.minecraft.server.v1_15_R1.ChunkTaskQueueSorter.b(SourceFile:58) ~[patched_1.15.2.jar:git-Paper-379]
	at net.minecraft.server.v1_15_R1.ThreadedMailbox.e(ThreadedMailbox.java:78) ~[patched_1.15.2.jar:git-Paper-379]
	at net.minecraft.server.v1_15_R1.ThreadedMailbox.a(ThreadedMailbox.java:121) ~[patched_1.15.2.jar:git-Paper-379]
	at net.minecraft.server.v1_15_R1.ThreadedMailbox.run(ThreadedMailbox.java:86) ~[patched_1.15.2.jar:git-Paper-379]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_261]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
```

**Comment by bergerkiller** [comment]
Judging by the stack trace, looks like an issue due to light cleaner. Likely the server lagged behind while setting light data, and the call only came back after the plugin was disabled. Probably best is to abort any callbacks that happen after disabling.
