### ISSUE TITLE
Error with Spigot 1.8.8 and latest BKCommonLib

### ISSUE THREAD

**Issue by NinCollin** [bergerhealer/BKCommonLib#131]
##### BkCommonLib version: 
BKCommonLib-1.17.1-v3-1117
##### Spigot version: 
1.8.8 (git-Spigot-21fe707-e1ebe52)

<hr>

#### Problem or bug: 
BKCommonLib throws the following error during initialization:
```
[15:25:44] [Server thread/INFO]: [BKCommonLib] Loading BKCommonLib v1.17.1-v3
[15:25:46] [Server thread/ERROR]: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @2114e8ff initializing BKCommonLib v1.17.1-v3 (Is it up to date?)
java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @2114e8ff
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.util.fast.ReflectionInvoker.create(ReflectionInvoker.java:106) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.util.fast.InitInvoker$InitGeneratedExecutableInvoker.create(InitInvoker.java:296) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.util.fast.InitInvoker.initializeInvoker(InitInvoker.java:75) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.util.fast.InitInvoker.invokeVA(InitInvoker.java:115) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.util.FastMethod.invokeVA(FastMethod.java:132) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.SafeMethod.invoke(SafeMethod.java:119) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonClassManipulation.writeClassData(CommonClassManipulation.java:68) ~[?:?]
	at com.bergerkiller.bukkit.common.PluginBase.rewriteClass(PluginBase.java:933) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonPlugin.onLoad(CommonPlugin.java:477) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:297) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.base/java.lang.Thread.run(Thread.java:831) [?:?]
[15:25:46] [Server thread/INFO]: [BKCommonLib] Enabling BKCommonLib v1.17.1-v3
[15:25:46] [Server thread/INFO]: [BKCommonLib] BKCommonLib is running on Spigot (git-Spigot-21fe707-e1ebe52) : v1_8_R3 (Minecraft 1.8.8)
```

#### Expected behaviour: 
No error is thrown on initialization

#### Steps to reproduce:
Run BuildTools.jar with the `--ver 1.8.8` flag, and then place the latest version of BKCommonLib into the plugins folder.

**Comment by yannicklamprecht** [comment]
Why you need the latest? You're 6 years behind with your server software. So it doesn't matter just use an outdated plugin.

**Comment by weeryan17** [comment]
BKCommonlib should actually support all the way back to 1.8, so this is in fact a bug

**Comment by weeryan17** [comment]
@NinCollin what java version are you running? I have a feeling that is part of the issue.

**Comment by bergerkiller** [comment]
![ScreenShot 2021-09-06 22 37 44](https://user-images.githubusercontent.com/957601/132259314-6b32c40f-fe1b-40e8-8cdd-2ad0bd94be28.jpg)
Ah, interesting. Yeah using JDK8 would fix your problem in this instance. BKCommonLib will work fine with that.

Still needs to be fixed though.

**Comment by bergerkiller** [comment]
Related issue: https://github.com/bergerhealer/BKCommonLib/issues/122

**Comment by NinCollin** [comment]
@weeryan17 I'm running OpenJDK 17
@bergerkiller Adding `--add-opens java.base/java.lang=ALL-UNNAMED` seems to make the error disappear, but it is replaced with a warning:
`[16:22:16 WARN]: Field 'private boolean a' in class null can not be found because class to find it in is null `
This may be expected of the workaround though as there are no other warnings or errors.

**Comment by bergerkiller** [comment]
That warning Ive seen too and seems to be normal. I think some class handle refers to a class in the server that doesnt exist, but since that class also isnt used it has no effect. So you can ignore it.
