### ISSUE TITLE
 [BKCommonLib.Network] Error occurred in onPacketSend handling PacketPlayOutMapChunk.

### ISSUE THREAD

**Issue by Vulpicula** [bergerhealer/BKCommonLib#136]
##### Spigot version: (Latest version of paper for 1.17)

<hr>

#### Steps to reproduce: Boot server with the latest version of BKLib and other plugins.

Console, since updating TrainCarts and related plugins last night, spits out this in perpetuity.
```
[23:52:30 ERROR]: [BKCommonLib.Network] Error occurred in onPacketSend handling PacketPlayOutMapChunk:
java.lang.NoSuchFieldError: tags
        at com.bergerkiller.bukkit.sl.SLListener.onPacketSend(SLListener.java:96) ~[SignLink-1.17.1-v1-54.jar:?]
        at com.bergerkiller.bukkit.common.internal.network.PacketHandlerHooked.handlePacketSend(PacketHandlerHooked.java:311) ~[BKCommonLib-1.18.1-v1-1172.jar:?]
        at com.bergerkiller.bukkit.common.internal.network.CommonPacketHandler$CommonChannelListener.write(CommonPacketHandler.java:129) ~[BKCommonLib-1.18.1-v1-1172.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.17.1.jar:git-Paper-399]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[patched_1.17.1.jar:git-Paper-399]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[patched_1.17.1.jar:git-Paper-399]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[patched_1.17.1.jar:git-Paper-399]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[patched_1.17.1.jar:git-Paper-399]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[patched_1.17.1.jar:git-Paper-399]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[patched_1.17.1.jar:git-Paper-399]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:450) ~[app:?]
        at net.minecraft.network.Connection.lambda$writePacket$8(Connection.java:424) ~[app:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[patched_1.17.1.jar:git-Paper-399]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[patched_1.17.1.jar:git-Paper-399]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[patched_1.17.1.jar:git-Paper-399]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.17.1.jar:git-Paper-399]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.17.1.jar:git-Paper-399]
```

**Comment by Vulpicula** [comment]
Some background research indicates this HAS happened before, a year or two ago: https://github.com/bergerhealer/BKCommonLib/issues/76

**Comment by bergerkiller** [comment]
You got to update SignLink to the 1.18-

I think you found out too lol

**Comment by Vulpicula** [comment]
> 

Turns out I shouldn't update plugins when sleep-deprived and about to go to bed. ;3
