### ISSUE TITLE
Dionysus (yet another 1.12.2 fork) support

### ISSUE THREAD

**Issue by RyanHecht** [bergerhealer/BKCommonLib#138]
If I have time I might have a go at implementing the necessary fixes to support [this fork](https://github.com/nopjmp/Dionysus). Making an issue upstream so I don't forget :p 

##### Spigot version:
[Dionysus](https://github.com/nopjmp/Dionysus) v0.1.12
<hr>

#### Problem or bug:
The following error when right clicking a TrainCart:
```
[00:08:48 ERROR]: [BKCommonLib.Network] [BKCommonLib] [Network] Failed to synchronize:
[00:08:48 WARN]: java.lang.NullPointerException                                                               
[00:08:48 WARN]:        at com.bergerkiller.generated.net.minecraft.server.NetworkManagerHandle.createQueuedPacket(NetworkManagerHandle.java:56)                                                                            [00:08:48 WARN]:        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker$mplgen118c9ecf.queuePacketUnsafe(GeneratedCodeInvoker$mplgen118c9ecf.java)                                                 
[00:08:48 WARN]:        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker$mplgen118c9ecf.invoke(GeneratedCodeInvoker$mplgen118c9ecf.java)                                                            
[00:08:48 WARN]:        at com.bergerkiller.mountiplex.reflection.util.fast.InitInvoker.invoke(InitInvoker.java:95)                                                                                                         [00:08:48 WARN]:        at com.bergerkiller.mountiplex.reflection.declarations.Template$StaticMethod$Converted.invoke(Template.java:1407)                                                                                   
[00:08:48 WARN]:        at com.bergerkiller.generated.net.minecraft.server.NetworkManagerHandle.queuePacketUnsafe(NetworkManagerHandle.java:24)                                                                             [00:08:48 WARN]:        at com.bergerkiller.generated.net.minecraft.server.PlayerConnectionHandle.queuePacket(PlayerConnectionHandle.java:70)                                                                               [00:08:48 WARN]:        at com.bergerkiller.generated.net.minecraft.server.PlayerConnectionHandle.queuePacket(PlayerConnectionHandle.java:79)                                                                               [00:08:48 WARN]:        at com.bergerkiller.bukkit.common.internal.network.PacketHandlerHooked.queuePacket(PacketHandlerHooked.java:229)                                                                                    [00:08:48 WARN]:        at com.bergerkiller.bukkit.common.utils.PacketUtil.queuePacket(PacketUtil.java:186)   [00:08:48 WARN]:        at com.bergerkiller.bukkit.common.utils.PacketUtil.queuePacket(PacketUtil.java:172)   
[00:08:48 WARN]:        at com.bergerkiller.bukkit.common.internal.mounting.VehicleMountHandler_BaseImpl.synchronizeAndQueuePackets(VehicleMountHandler_BaseImpl.java:377)                                                  
[00:08:48 WARN]:        at com.bergerkiller.bukkit.common.internal.mounting.VehicleMountHandler_BaseImpl.mount(VehicleMountHandler_BaseImpl.java:69)                                                                       
[00:08:48 WARN]:        at com.bergerkiller.bukkit.tc.attachments.control.seat.SeatedEntityNormal.makeVisible(SeatedEntityNormal.java:137) 
[00:08:48 WARN]:        at com.bergerkiller.bukkit.tc.attachments.control.seat.FirstPersonDefault.makeVisible(FirstPersonDefault.java:98)
[00:08:48 WARN]:        at com.bergerkiller.bukkit.tc.attachments.control.CartAttachmentSeat.makeVisibleImpl(CartAttachmentSeat.java:218)
[00:08:48 WARN]:        at com.bergerkiller.bukkit.tc.attachments.control.CartAttachmentSeat.setEntity(CartAttachmentSeat.java:322)
[00:08:48 WARN]:        at com.bergerkiller.bukkit.tc.controller.components.AttachmentControllerMember.onSyncPassengers(AttachmentControllerMember.java:141)
[00:08:48 WARN]:        at com.bergerkiller.bukkit.tc.controller.MinecartMemberNetwork.onSyncPassengers(MinecartMemberNetwork.java:73)
[00:08:48 WARN]:        at com.bergerkiller.bukkit.common.controller.EntityNetworkController.syncPassengers(EntityNetworkController.java:909)
[00:08:48 WARN]:        at com.bergerkiller.bukkit.tc.controller.MinecartMemberNetwork.onTick(MinecartMemberNetwork.java:132)
[00:08:48 WARN]:        at com.bergerkiller.bukkit.common.internal.hooks.EntityTrackerEntryHook_1_8_to_1_13_2.track(EntityTrackerEntryHook_1_8_to_1_13_2.java:44)
[00:08:48 WARN]:        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedMethodInvoker$mplgen3478b93b.invokeVA(Unknown Source)
[00:08:48 WARN]:        at com.bergerkiller.mountiplex.reflection.ClassInterceptor$CallbackMethodInterceptor.invokeVA(ClassInterceptor.java:506)
[00:08:48 WARN]:        at com.bergerkiller.mountiplex.reflection.util.fast.Invoker.invoke(Invoker.java:33)
[00:08:48 WARN]:        at net.minecraft.server.v1_12_R1.EntityTrackerEntry$mplgen12c38c01.track(Unknown Source)
[00:08:48 WARN]:        at net.minecraft.server.v1_12_R1.EntityTracker.updatePlayers(EntityTracker.java:182)
[00:08:48 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:961)
[00:08:48 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
[00:08:48 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:775)
[00:08:48 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[00:08:48 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by bergerkiller** [comment]
If you look further up, probably during loading or enabling of bkcommonlib, there will be an error about this which explains what happened. I'll fix the code a bit so it doesnt throw a meaningless NPE when this happens.

https://github.com/bergerhealer/BKCommonLib/commit/e56c6eeec800a216e0178914b449c27766e66e05

The code here tries to create a QueuedPacket instance, given a Packet.

https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/java/com/bergerkiller/generated/net/minecraft/network/NetworkManagerHandle.java#L34

**Comment by bergerkiller** [comment]
A little clarification

This queued packet / queuePacket() function is explicitly so it is safe to enqueue (send) packets while inside the listener for other packets. Calling sendPacket() resulted in a randomly occurring deadlock (due to netty multithreading). This method avoids that by throwing it into the to-send queue instead, never entering the sendPacket() routine on the calling thread.

Most likely this patch broke it https://github.com/nopjmp/Dionysus/blob/dev/patches/server/0018-Optimize-Network-Manager.patch

I can probably clean up the code a bit, it has some deprecated old-style template stuff in there that can be cleaned up. I do need to know what is an appropriate queuePacket() implementation for Dionysus.

**Comment by bergerkiller** [comment]
See also: https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/templates/com/bergerkiller/templates/net/minecraft/network/manager.txt#L20

**Comment by RyanHecht** [comment]
Thanks, I appreciate all the hints! Posting the stacktrace that shows up on BKCL enable for posterity:
```
[00:07:16] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_12_R1.NetworkManager$QueuedPacket.<init>(net.minecraft.server.v1_12_R1.Packet, [Lio.netty.util.concurrent.GenericFutureListener;)
[00:07:16] [Server thread/WARN]: 	at java.lang.Class.getConstructor0(Class.java:3082)
[00:07:16] [Server thread/WARN]: 	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
[00:07:16] [Server thread/WARN]: 	at com.bergerkiller.generated.net.minecraft.server.NetworkManagerHandle.<clinit>(NetworkManagerHandle.java:45)
[00:07:16] [Server thread/WARN]: 	at com.bergerkiller.generated.net.minecraft.server.PlayerConnectionHandle.<clinit>(PlayerConnectionHandle.java:33)
[00:07:16] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.internal.network.PacketHandlerHooked.onEnable(PacketHandlerHooked.java:46)
[00:07:16] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.internal.network.CommonPacketHandler.onEnable(CommonPacketHandler.java:38)
[00:07:16] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.internal.CommonPlugin.updatePacketHandler(CommonPlugin.java:334)
[00:07:16] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.internal.CommonPlugin.enable(CommonPlugin.java:493)
[00:07:16] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:778)
[00:07:16] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[00:07:16] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[00:07:16] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[00:07:16] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[00:07:16] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[00:07:16] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:227)
[00:07:16] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[00:07:16] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by RyanHecht** [comment]
I haven't locally cloned/patched Dionysus yet but when I do I'll post the queuePacket implementations they have

**Comment by bergerkiller** [comment]
Made the code a little less painful to work with in preparation for any changes needed.

https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/templates/com/bergerkiller/templates/net/minecraft/network/manager.txt#L36

**Comment by RyanHecht** [comment]
It looks like the only `QueuedPacket` constructor is as follows:
`QueuedPacket(Packet<?> packet, GenericFutureListener<? extends Future<? super Void>> agenericfuturelistener)`

...what's the difference between this and the constructor on the first line of the `ifexists` in https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/templates/com/bergerkiller/templates/net/minecraft/network/manager.txt#L36 ? Is it because `GenericFutureListener` isn't paramaterized as it's expecting?

**Comment by bergerkiller** [comment]
That shouldn't matter, but is the QueuedPacket class still inside the NetworkManager class? Or is it elsewhere?

**Comment by RyanHecht** [comment]
Yeah, it's still `NetworkManager.QueuedPacket`

**Comment by bergerkiller** [comment]
Just to make sure, you have tried the latest build of bkcl, and it gives the #error over there? Because in a previous version it did a >= 1.13 version check, and now it just checks for the constructors. So maybe I accidentally fixed it already

**Comment by RyanHecht** [comment]
Well would you look that that...that's exactly what happened :p 
Going to close this issue, thanks so much for the help!
