### ISSUE TITLE
An error occurs when used on a server with cubic chunk.

### ISSUE THREAD

**Issue by RuNan2** [bergerhealer/BKCommonLib#139]
##### Mohist version: 1.12.2 build #307

<hr>

#### Problem or bug:
```
[17:38:13 ERROR]: [BKCommonLib] Unhandled exception occured in onPacketSending(PacketEvent) for BKCommonLib
 java.lang.RuntimeException: Token serializer not found: moe.plushie.armourers_workshop.common.init.entities.EntityMannequin$DataSerializerBipedRotations@122c213c
        at com.bergerkiller.bukkit.common.wrappers.DataWatcher$Key.<init>(DataWatcher.java:533) ~[BKCommonLib-1.18.1-v3-SNAPSHOT-1243.jar:?]
        at com.bergerkiller.bukkit.common.wrappers.DataWatcher$Key.<init>(DataWatcher.java:524) ~[BKCommonLib-1.18.1-v3-SNAPSHOT-1243.jar:?]
        at com.bergerkiller.bukkit.common.conversion.type.WrapperConversion.toKey(WrapperConversion.java:489) ~[BKCommonLib-1.18.1-v3-SNAPSHOT-1243.jar:?]
        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen21cbc8f0.invoke(Unknown Source) ~[?:?]
        at com.bergerkiller.mountiplex.conversion.type.AnnotatedConverter.convertInput(AnnotatedConverter.java:50) ~[BKCommonLib-1.18.1-v3-SNAPSHOT-1243.jar:?]
        at com.bergerkiller.mountiplex.conversion.Converter.convert(Converter.java:47) ~[BKCommonLib-1.18.1-v3-SNAPSHOT-1243.jar:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Field$Converted.get(Template.java:2221) ~[BKCommonLib-1.18.1-v3-SNAPSHOT-1243.jar:?]
        at com.bergerkiller.bukkit.common.wrappers.DataWatcher$Item.getKey(DataWatcher.java:385) ~[BKCommonLib-1.18.1-v3-SNAPSHOT-1243.jar:?]
        at com.bergerkiller.bukkit.common.wrappers.DataWatcher$Item.translate(DataWatcher.java:366) ~[BKCommonLib-1.18.1-v3-SNAPSHOT-1243.jar:?]
        at com.bergerkiller.bukkit.common.internal.map.CommonMapController.hasMapItemInMetadata(CommonMapController.java:795) ~[BKCommonLib-1.18.1-v3-SNAPSHOT-1243.jar:?]
        at com.bergerkiller.bukkit.common.internal.map.CommonMapController.onPacketSend(CommonMapController.java:717) ~[BKCommonLib-1.18.1-v3-SNAPSHOT-1243.jar:?]
        at com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketListener.onPacketSending(ProtocolLibPacketHandler.java:411) ~[BKCommonLib-1.18.1-v3-SNAPSHOT-1243.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.7.0]
        at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:249) [gw.class:?]
        at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java:181) [gw.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147359_a(NetHandlerPlayServer.java:1326) [pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_147359_a(NetworkDispatcher.java:213) [NetworkDispatcher$1.class:?]
        at net.minecraft.entity.EntityTrackerEntry.func_73117_b(EntityTrackerEntry.java:427) [os.class:?]
        at net.minecraft.entity.EntityTracker.sendLeashedEntitiesInCube(EntityTracker.java:577) [ol.class:?]
        at io.github.opencubicchunks.cubicchunks.core.server.CubeWatcher.addPlayer(CubeWatcher.java:118) [CubeWatcher.class:?]
        at io.github.opencubicchunks.cubicchunks.core.server.PlayerCubeMap.func_72693_b(PlayerCubeMap.java:465) [PlayerCubeMap.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:351) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:884) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_321]
[17:38:13 ERROR]: Parameters:
  net.minecraft.network.play.server.SPacketEntityMetadata@30e56e46[
    field_149379_a=38
    field_149378_b=[net.minecraft.network.datasync.EntityDataManager$DataEntry@2bb09ff, net.minecraft.network.datasync.EntityDataManager$DataEntry@657c1d7, net.minecraft.network.datasync.EntityDataManager$DataEntry@2ca5d404, net.minecraft.network.datasync.EntityDataManager$DataEntry@dbeca7d, net.minecraft.network.datasync.EntityDataManager$DataEntry@5710dec4, net.minecraft.network.datasync.EntityDataManager$DataEntry@6f71e488, net.minecraft.network.datasync.EntityDataManager$DataEntry@6df60896, net.minecraft.network.datasync.EntityDataManager$DataEntry@1660ca77, net.minecraft.network.datasync.EntityDataManager$DataEntry@47d7d081, net.minecraft.network.datasync.EntityDataManager$DataEntry@27e22957, net.minecraft.network.datasync.EntityDataManager$DataEntry@7a8d2785, net.minecraft.network.datasync.EntityDataManager$DataEntry@6aae79d1, net.minecraft.network.datasync.EntityDataManager$DataEntry@1304efdd, net.minecraft.network.datasync.EntityDataManager$DataEntry@259ad47b, net.minecraft.network.datasync.EntityDataManager$DataEntry@36b86e42, net.minecraft.network.datasync.EntityDataManager$DataEntry@2f41e9b5]
  ]
[17:38:14 ERROR]: [BKCommonLib] Unhandled exception occured in onPacketSending(PacketEvent) for BKCommonLib
 java.lang.RuntimeException: Token serializer not found: moe.plushie.armourers_workshop.common.init.entities.EntityMannequin$DataSerializerBipedRotations@122c213c
        at com.bergerkiller.bukkit.common.wrappers.DataWatcher$Key.<init>(DataWatcher.java:533) ~[BKCommonLib-1.18.1-v3-SNAPSHOT-1243.jar:?]
        at com.bergerkiller.bukkit.common.wrappers.DataWatcher$Key.<init>(DataWatcher.java:524) ~[BKCommonLib-1.18.1-v3-SNAPSHOT-1243.jar:?]
        at com.bergerkiller.bukkit.common.conversion.type.WrapperConversion.toKey(WrapperConversion.java:489) ~[BKCommonLib-1.18.1-v3-SNAPSHOT-1243.jar:?]
        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen21cbc8f0.invoke(Unknown Source) ~[?:?]
        at com.bergerkiller.mountiplex.conversion.type.AnnotatedConverter.convertInput(AnnotatedConverter.java:50) ~[BKCommonLib-1.18.1-v3-SNAPSHOT-1243.jar:?]
        at com.bergerkiller.mountiplex.conversion.Converter.convert(Converter.java:47) ~[BKCommonLib-1.18.1-v3-SNAPSHOT-1243.jar:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Field$Converted.get(Template.java:2221) ~[BKCommonLib-1.18.1-v3-SNAPSHOT-1243.jar:?]
        at com.bergerkiller.bukkit.common.wrappers.DataWatcher$Item.getKey(DataWatcher.java:385) ~[BKCommonLib-1.18.1-v3-SNAPSHOT-1243.jar:?]
        at com.bergerkiller.bukkit.common.wrappers.DataWatcher$Item.translate(DataWatcher.java:366) ~[BKCommonLib-1.18.1-v3-SNAPSHOT-1243.jar:?]
        at com.bergerkiller.bukkit.common.internal.map.CommonMapController.hasMapItemInMetadata(CommonMapController.java:795) ~[BKCommonLib-1.18.1-v3-SNAPSHOT-1243.jar:?]
        at com.bergerkiller.bukkit.common.internal.map.CommonMapController.onPacketSend(CommonMapController.java:717) ~[BKCommonLib-1.18.1-v3-SNAPSHOT-1243.jar:?]
        at com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketListener.onPacketSending(ProtocolLibPacketHandler.java:411) ~[BKCommonLib-1.18.1-v3-SNAPSHOT-1243.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.7.0]
        at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:249) [gw.class:?]
        at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java:181) [gw.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147359_a(NetHandlerPlayServer.java:1326) [pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_147359_a(NetworkDispatcher.java:213) [NetworkDispatcher$1.class:?]
        at net.minecraft.entity.EntityTrackerEntry.func_73117_b(EntityTrackerEntry.java:427) [os.class:?]
        at net.minecraft.entity.EntityTracker.sendLeashedEntitiesInCube(EntityTracker.java:577) [ol.class:?]
        at io.github.opencubicchunks.cubicchunks.core.server.PlayerCubeMap.func_72693_b(PlayerCubeMap.java:512) [PlayerCubeMap.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:351) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:884) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_321]
[17:38:14 ERROR]: Parameters:
  net.minecraft.network.play.server.SPacketEntityMetadata@3a171652[
    field_149379_a=75
    field_149378_b=[net.minecraft.network.datasync.EntityDataManager$DataEntry@2b666bf9, net.minecraft.network.datasync.EntityDataManager$DataEntry@2212743, net.minecraft.network.datasync.EntityDataManager$DataEntry@224c75bf, net.minecraft.network.datasync.EntityDataManager$DataEntry@20eb5222, net.minecraft.network.datasync.EntityDataManager$DataEntry@38cacc65, net.minecraft.network.datasync.EntityDataManager$DataEntry@33daef00, net.minecraft.network.datasync.EntityDataManager$DataEntry@727a8549, net.minecraft.network.datasync.EntityDataManager$DataEntry@87ab366, net.minecraft.network.datasync.EntityDataManager$DataEntry@66bdffe8, net.minecraft.network.datasync.EntityDataManager$DataEntry@2fbbed0, net.minecraft.network.datasync.EntityDataManager$DataEntry@240d330b, net.minecraft.network.datasync.EntityDataManager$DataEntry@7931556f, net.minecraft.network.datasync.EntityDataManager$DataEntry@70fab71e, net.minecraft.network.datasync.EntityDataManager$DataEntry@2fa88aef, net.minecraft.network.datasync.EntityDataManager$DataEntry@6270717a, net.minecraft.network.datasync.EntityDataManager$DataEntry@1199ca76]
  ]
[17:39:57 ERROR]: The server has stopped responding!
[17:39:57 ERROR]: Mohist version: git-Mohist-1.12.2-307 (MC: 1.12.2)
[17:39:57 ERROR]: Memory using: 4947MB/8192MB/8192MB
[17:39:57 ERROR]: ------------------------------
[17:39:57 ERROR]: Server thread dump (Look for plugins here before reporting to Mohist!):
[17:39:57 ERROR]: ------------------------------
[17:39:57 ERROR]: Current Thread: Server thread
[17:39:57 ERROR]:       PID: 24 | Suspended: false | Native: true | State: RUNNABLE
[17:39:57 ERROR]:       Stack:
[17:39:57 ERROR]:               sun.nio.fs.WindowsNativeDispatcher.CreateFile0(Native Method)
[17:39:57 ERROR]:               sun.nio.fs.WindowsNativeDispatcher.CreateFile(Unknown Source)
[17:39:57 ERROR]:               sun.nio.fs.WindowsChannelFactory.open(Unknown Source)
[17:39:58 ERROR]:               java.lang.Thread.run(Unknown Source)
[17:39:58 ERROR]: ------------------------------
[17:39:58 ERROR]: Current Thread: Skript variable save thread for database 'default'
[17:39:58 ERROR]:       PID: 155 | Suspended: false | Native: false | State: WAITING
[17:39:58 ERROR]:       Stack:
[17:39:58 ERROR]:               sun.misc.Unsafe.park(Native Method)
[17:39:58 ERROR]:               java.util.concurrent.locks.LockSupport.park(Unknown Source)
[17:39:58 ERROR]:               java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
[17:39:58 ERROR]:               java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
[17:39:58 ERROR]:               java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[17:39:58 ERROR]:               java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[17:39:58 ERROR]:               java.lang.Thread.run(Unknown Source)
[17:39:58 ERROR]: ------------------------------
[17:39:58 ERROR]: Current Thread: bStats-Metrics
[17:39:58 ERROR]:       PID: 91 | Suspended: false | Native: false | State: TIMED_WAITING
[17:39:58 ERROR]:       Stack:
[17:39:58 ERROR]:               sun.misc.Unsafe.park(Native Method)
[17:39:58 ERROR]:               java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
[17:39:58 ERROR]:               java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
[17:39:58 ERROR]:       Thread is waiting on monitor(s):
[17:39:58 ERROR]:               Locked on:java.io.PrintStream.write(Unknown Source)
[17:39:58 ERROR]:       Stack:
[17:39:58 ERROR]:               org.fusesource.jansi.internal.Kernel32.SetConsoleTextAttribute(Native Method)
[17:39:58 ERROR]:               org.fusesource.jansi.WindowsAnsiOutputStream.applyAttribute(WindowsAnsiOutputStream.java:117)
[17:39:58 ERROR]:               org.fusesource.jansi.WindowsAnsiOutputStream.processAttributeRest(WindowsAnsiOutputStream.java:245)
[17:39:58 ERROR]:               org.fusesource.jansi.AnsiOutputStream.processEscapeCommand(AnsiOutputStream.java:287)
[17:39:58 ERROR]:               org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:125)
[17:39:58 ERROR]:               java.io.FilterOutputStream.write(Unknown Source)
[17:39:58 ERROR]:               java.io.PrintStream.write(Unknown Source)
[17:39:58 ERROR]:               java.io.FilterOutputStream.write(Unknown Source)
[17:39:58 ERROR]:               org.bukkit.craftbukkit.v1_12_R1.util.TerminalConsoleWriterThread.run(TerminalConsoleWriterThread.java:37)
[17:39:58 ERROR]:               java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[17:39:58 ERROR]:               java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[17:39:58 ERROR]:               java.lang.Thread.run(Unknown Source)
[17:39:58 ERROR]: ------------------------------
[17:39:58 ERROR]: Current Thread: DestroyJavaVM
[17:39:58 ERROR]:       PID: 27 | Suspended: false | Native: false | State: RUNNABLE
[17:39:58 ERROR]:       Stack:
[17:39:58 ERROR]: ------------------------------
[17:39:58 ERROR]: Current Thread: Server thread
[17:39:58 ERROR]:       PID: 24 | Suspended: false | Native: false | State: RUNNABLE
[17:39:58 ERROR]:       Stack:
[17:39:58 ERROR]:               sun.nio.fs.WindowsNativeDispatcher.CreateFile0(Native Method)
[17:39:58 ERROR]:               sun.nio.fs.WindowsNativeDispatcher.CreateFile(Unknown Source)
[17:39:58 ERROR]:               sun.nio.fs.WindowsChannelFactory.open(Unknown Source)
[17:39:58 ERROR]:               sun.nio.fs.WindowsChannelFactory.newFileChannel(Unknown Source)
[17:39:58 ERROR]:               sun.nio.fs.WindowsFileSystemProvider.newFileChannel(Unknown Source)
[17:39:58 ERROR]:               java.nio.channels.FileChannel.open(Unknown Source)
[17:39:58 ERROR]:               java.nio.channels.FileChannel.open(Unknown Source)
[17:39:58 ERROR]:               io.github.opencubicchunks.cubicchunks.core.server.chunkio.region.ShadowPagingRegion$Builder.build(ShadowPagingRegion.java:305)
[17:39:58 ERROR]:               io.github.opencubicchunks.cubicchunks.core.server.chunkio.RegionCubeStorage.lambda$saveForPath$4(RegionCubeStorage.java:101)
[17:39:58 ERROR]:               io.github.opencubicchunks.cubicchunks.core.server.chunkio.RegionCubeStorage$$Lambda$828/1372863727.create(Unknown Source)
[17:39:58 ERROR]:               cubicchunks.regionlib.lib.provider.SimpleRegionProvider.forAllRegions(SimpleRegionProvider.java:124)
[17:39:58 ERROR]:               cubicchunks.regionlib.lib.provider.SharedCachedRegionProvider.forAllRegions(SharedCachedRegionProvider.java:136)
[17:39:58 ERROR]:               cubicchunks.regionlib.api.storage.SaveSection.forAllKeys(SaveSection.java:209)
[17:39:58 ERROR]:               io.github.opencubicchunks.cubicchunks.core.server.chunkio.RegionCubeStorage.forEachCube(RegionCubeStorage.java:241)
[17:39:58 ERROR]:               com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker$mplgen2e184db7.forEachCube(GeneratedCodeInvoker$mplgen2e184db7.java)
[17:39:58 ERROR]:               com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker$mplgen2e184db7.invoke(GeneratedCodeInvoker$mplgen2e184db7.java)
[17:39:58 ERROR]:               com.bergerkiller.mountiplex.reflection.util.fast.InitInvoker.invoke(InitInvoker.java:95)
[17:39:58 ERROR]:               com.bergerkiller.bukkit.common.internal.logic.RegionHandler_CubicChunks_1_12_2$CubicChunksHandle$impl.forEachCube(Unknown Source)
[17:39:58 ERROR]:               com.bergerkiller.bukkit.common.internal.logic.RegionHandler_CubicChunks_1_12_2.getRegions3(RegionHandler_CubicChunks_1_12_2.java:131)
[17:39:58 ERROR]:               com.bergerkiller.bukkit.common.internal.logic.RegionHandlerSelector.getRegions3(RegionHandlerSelector.java:81)
[17:39:58 ERROR]:               com.bergerkiller.bukkit.common.utils.WorldUtil.getWorldRegions3(WorldUtil.java:1199)
[17:39:58 ERROR]:               com.bergerkiller.bukkit.lightcleaner.util.FlatRegionInfoMap.create(FlatRegionInfoMap.java:163)
[17:39:58 ERROR]:               com.bergerkiller.bukkit.lightcleaner.lighting.LightingTaskWorld.lambda$process$0(LightingTaskWorld.java:73)
[17:39:58 ERROR]:               com.bergerkiller.bukkit.lightcleaner.lighting.LightingTaskWorld$$Lambda$1889/12315090.run(Unknown Source)
[17:39:58 ERROR]:               com.bergerkiller.bukkit.common.internal.CommonNextTickExecutor$ExecutorTask.run(CommonNextTickExecutor.java:164)
[17:39:58 ERROR]:               org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[17:39:58 ERROR]:               org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:422)
[17:39:58 ERROR]:               net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:831)
[17:39:58 ERROR]:               net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
[17:39:58 ERROR]:               net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778)
[17:39:58 ERROR]:               net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624)
[17:39:58 ERROR]:               java.lang.Thread.run(Unknown Source)
[17:39:58 ERROR]: ------------------------------
[17:39:58 ERROR]: Current Thread: Server Infinisleeper
[17:39:58 ERROR]:       PID: 25 | Suspended: false | Native: false | State: TIMED_WAITING
[17:39:58 ERROR]:       Stack:
[17:39:58 ERROR]:               java.lang.Thread.sleep(Native Method)
[17:39:58 ERROR]:               net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:96)
[17:39:58 ERROR]: ------------------------------
[17:39:58 ERROR]: Current Thread: NonBlockingInputStreamThread
[17:39:58 ERROR]:       PID: 22 | Suspended: false | Native: false | State: WAITING
[17:39:58 ERROR]:       Stack:
[17:39:58 ERROR]:               java.lang.Object.wait(Native Method)
[17:39:58 ERROR]:               jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:275)
[17:39:58 ERROR]:               java.lang.Thread.run(Unknown Source)
[17:39:58 ERROR]: ------------------------------
[17:39:58 ERROR]: Current Thread: Snooper Timer
[17:39:58 ERROR]:       PID: 20 | Suspended: false | Native: false | State: TIMED_WAITING
[17:39:58 ERROR]:       Stack:
[17:39:58 ERROR]:               java.lang.Object.wait(Native Method)
[17:39:58 ERROR]:               java.util.TimerThread.mainLoop(Unknown Source)
[17:39:58 ERROR]:               java.util.TimerThread.run(Unknown Source)
[17:39:58 ERROR]: ------------------------------
[17:39:58 ERROR]: Current Thread: Mohist Async Task Handler Thread - 1
[17:39:58 ERROR]:       PID: 19 | Suspended: false | Native: false | State: WAITING
[17:39:58 ERROR]:       Stack:
[17:39:58 ERROR]:               sun.misc.Unsafe.park(Native Method)
[17:39:58 ERROR]:               java.util.concurrent.locks.LockSupport.park(Unknown Source)
[17:39:58 ERROR]:               java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
[17:39:58 ERROR]:               java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
[17:39:58 ERROR]:               java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
[17:39:58 ERROR]:               java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[17:39:58 ERROR]:               java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[17:39:58 ERROR]:               java.lang.Thread.run(Unknown Source)
[17:39:58 ERROR]: ------------------------------
[17:39:58 ERROR]: Current Thread: Attach Listener
[17:39:58 ERROR]:       PID: 6 | Suspended: false | Native: false | State: RUNNABLE
[17:39:58 ERROR]:       Stack:
[17:39:58 ERROR]: ------------------------------
[17:39:58 ERROR]: Current Thread: Signal Dispatcher
[17:39:58 ERROR]:       PID: 5 | Suspended: false | Native: false | State: RUNNABLE
[17:39:58 ERROR]:       Stack:
[17:39:58 ERROR]: ------------------------------
[17:39:58 ERROR]: Current Thread: Finalizer
[17:39:58 ERROR]:       PID: 3 | Suspended: false | Native: false | State: WAITING
[17:39:58 ERROR]:       Stack:
[17:39:58 ERROR]:               java.lang.Object.wait(Native Method)
[17:39:58 ERROR]:               java.lang.ref.ReferenceQueue.remove(Unknown Source)
[17:39:58 ERROR]:               java.lang.ref.ReferenceQueue.remove(Unknown Source)
[17:39:58 ERROR]:               java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)
[17:39:58 ERROR]: ------------------------------
[17:39:58 ERROR]: Current Thread: Reference Handler
[17:39:58 ERROR]:       PID: 2 | Suspended: false | Native: false | State: WAITING
[17:39:58 ERROR]:       Stack:
[17:39:58 ERROR]:               java.lang.Object.wait(Native Method)
[17:39:58 ERROR]:               java.lang.Object.wait(Unknown Source)
[17:39:58 ERROR]:               java.lang.ref.Reference.tryHandlePending(Unknown Source)
[17:39:58 ERROR]:               java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)
[17:39:58 ERROR]: ------------------------------
[17:39:58 INFO]: Java has been asked to exit (code 0)
[17:39:58 INFO]: Exit trace:
[17:39:58 INFO]:        org.spigotmc.WatchdogThread.run(WatchdogThread.java:85)
[17:39:58 INFO]: Stopping server
```

#### Server Plugins/Mods
Plugins:
BKCommonLib-1.18.1-v3-SNAPSHOT-1243
Clearlag
Skript 2.2 dev36
SkEtcR v3.3
ProtocolLib
EssentialsX-2.19.2
bgmplay-1.0.7-RELEASE
DiscordSRV-Build-1.24.0
GomSK
LightCleaner-1.18.1-v4-SNAPSHOT-134
multiworld
PlaceholderAPI-2.11.1
SkChoke
WorldEdit-6.1.9-0.3-SNAPSHOT-all
Vault 
HolographicDisplays
FKeyCommand
TAB.v3.0.2
skRayFall+v1.9.25

Mods:
CubicChunks-1.12.2-0.0.1208.0-SNAPSHOT-all
Armourers-Workshop-1.12.2-0.51.0
BiomesOPlenty-1.12.2-7.0.1.2445-universal
Pixelmon-1.12.2-8.3.6
CreativeCore_v1.10.69_mc1.12.2
CustomNPCs_1.12.2-(05Jul20)
LittleFrames_v1.0.12_mc1.12.2
LittleTiles_v1.5.57_mc1.12.2

#### Similar issue:
https://github.com/bergerhealer/BKCommonLib/issues/114#issue-783772219

**Comment by bergerkiller** [comment]
This is a known issue, cubic chunks doesnt yet offer a fast api to figure out all the regions that exist for a server. So instead it iterates all 16x16x16 cubes, which on large worlds, is very slow.

Workaround is to update to this build: https://ci.mg-dev.eu/job/Light-Cleaner/134/

And use /cleanlight loaded

(with optional flags, such as /cleanlight 20 loaded)

It then only operates on loaded chunks, avoiding the loop by all cubes. Can leave this issue ticket open.

**Comment by bbayu123** [comment]
Closing issue, workaround suggested.
