### ISSUE TITLE
Crashed with Arclight(1.0.3) [1.18]

### ISSUE THREAD

**Issue by CornWorld** [bergerhealer/BKCommonLib#143]
##### Spigot version: 1.18.2-R0.1-SNAPSHOT

<hr>

#### Expected behaviour:
[crash-2022-05-02_09.40.42-server.txt](https://github.com/bergerhealer/BKCommonLib/files/8600389/crash-2022-05-02_09.40.42-server.txt)
[debug.log](https://github.com/bergerhealer/BKCommonLib/files/8600411/debug.log)
[latest.log](https://github.com/bergerhealer/BKCommonLib/files/8600412/latest.log)

#### Steps to reproduce:
1. Download `arclight-forge-1.18.2-1.0.3.jar`.
2. Download `bellsoft-jdk18.0.1+12-windows-amd64.msi`, and install it.
3. Run `arclight-forge-1.18.2-1.0.3.jar` in a empty folder(it will download lib files), and allow the eula.
5. Start the server, if it runs well, stop it, remove worlds folder.
6. Download `BKCommonLib-1.18.2-v1-1265.jar`, and put into `plugins` folder.
7. Run `arclight-forge-1.18.2-1.0.3.jar`, and it crashed with a lot of outputs.

**Comment by bergerkiller** [comment]
It's been nearly a year now, is this issue still happening with the latest bkcl dev build? Kinda lost track, may have fixed stuff in the meantime

**Comment by CornWorld** [comment]
I'm sorry but I could not test again for the moment.

**Comment by Algustine** [comment]
> It's been nearly a year now, is this issue still happening with the latest bkcl dev build? Kinda lost track, may have fixed stuff in the meantime

Hi, I am also using a Arclight 1.18 server. On my server it does not contribute to a server crash, but still, it fails to load.

---

Using the latest Modrinth build: BKCommonLib 1.19.4-v1
Arclight version: arclight-1.18.2-1.0.8-e80a33d2
Spigot: v1_18_R2
JVM: build 17.0.6+9-LTS-190

---
### Relevant debug info
```
 [174月2023 23:31:12.222] [Server thread/ERROR] [BKCommonLib/]: An error occurred while loading
java.lang.ExceptionInInitializerError: null
	at com.bergerkiller.bukkit.common.internal.CommonPlugin.onLoad(CommonPlugin.java:530) ~[?:?] {}
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServerMixin.java:412) ~[arclight-1.18.2-1.0.8-e80a33d2.jar%2369!/:arclight-1.18.2-1.0.8-e80a33d2] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,re:mixin}
	at net.minecraft.server.dedicated.DedicatedServer.handler$zcj000$arclight$loadPlugins(DedicatedServerMixin.java:694) ~[server-1.18.2-20220404.173914-srg.jar%2380!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:167) ~[server-1.18.2-20220404.173914-srg.jar%2380!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2099) ~[server-1.18.2-20220404.173914-srg.jar%2380!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:261) ~[server-1.18.2-20220404.173914-srg.jar%2380!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin,re:mixin}
Caused by: java.lang.NullPointerException: Cannot invoke "com.bergerkiller.bukkit.common.internal.cdn.MojangSpigotRemapper.remapMethodNameReverse(java.lang.Class, String, java.lang.Class[], String)" because "this.mojangSpigotRemapper" is null
	at com.bergerkiller.bukkit.common.server.CraftBukkitServer.resolveMethodAlias(CraftBukkitServer.java:278) ~[?:?] {}
	at com.bergerkiller.mountiplex.reflection.resolver.ChainResolver.lambda$chain$5(ChainResolver.java:154) ~[?:?] {}
	at com.bergerkiller.mountiplex.reflection.resolver.Resolver.resolveMethodAlias(Resolver.java:411) ~[?:?] {}
	at com.bergerkiller.mountiplex.reflection.declarations.MethodDeclaration.<init>(MethodDeclaration.java:62) ~[?:?] {}
	at com.bergerkiller.mountiplex.conversion.Conversion.registerConverters(Conversion.java:142) ~[?:?] {}
	at com.bergerkiller.bukkit.common.internal.CommonBootstrap.initResolvers(CommonBootstrap.java:752) ~[?:?] {}
	at com.bergerkiller.bukkit.common.internal.CommonBootstrap.initCommonServer(CommonBootstrap.java:272) ~[?:?] {}
	at com.bergerkiller.bukkit.common.Common.<clinit>(Common.java:131) ~[?:?] {}
	... 7 more

[174月2023 23:31:14.059] [Server thread/ERROR] [BKCommonLib/]: An unexpected BKCommonLib initialization error occurred
java.lang.NoClassDefFoundError: Could not initialize class com.bergerkiller.bukkit.common.Common
	at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:698) ~[?:?] {}
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:264) ~[arclight-1.18.2-1.0.8-e80a33d2.jar%2369!/:arclight-1.18.2-1.0.8-e80a33d2] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginMixin,pl:mixin:A,re:mixin}
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight-1.18.2-1.0.8-e80a33d2.jar%2369!/:arclight-1.18.2-1.0.8-e80a33d2] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginLoaderMixin,pl:mixin:A}
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[arclight-1.18.2-1.0.8-e80a33d2.jar%2369!/:arclight-1.18.2-1.0.8-e80a33d2] {re:mixin,re:classloading}
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServerMixin.java:518) ~[arclight-1.18.2-1.0.8-e80a33d2.jar%2369!/:arclight-1.18.2-1.0.8-e80a33d2] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,re:mixin}
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServerMixin.java:432) ~[arclight-1.18.2-1.0.8-e80a33d2.jar%2369!/:arclight-1.18.2-1.0.8-e80a33d2] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,re:mixin}
	at net.minecraft.server.dedicated.DedicatedServer.handler$zcj000$arclight$loadPlugins(DedicatedServerMixin.java:695) ~[server-1.18.2-20220404.173914-srg.jar%2380!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:167) ~[server-1.18.2-20220404.173914-srg.jar%2380!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2099) ~[server-1.18.2-20220404.173914-srg.jar%2380!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:261) ~[server-1.18.2-20220404.173914-srg.jar%2380!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin,re:mixin}
[174月2023 23:31:14.059] [Server thread/ERROR] [BKCommonLib/]: BKCommonLib and all depending plugins will now disable...
[174月2023 23:31:14.071] [Server thread/INFO] [BKCommonLib/]: null
```

**Comment by Algustine** [comment]
It has now become a little weird for me. bkcl cannot be loaded yesterday all day, neither on server or on my laptop, but today when I do the troubleshoots, it is loaded with no error occur.

1. Tried to perform a fresh arclight install on my laptop and loaded bkcl, no errors, and then with all mods and plugins, still no erros.
2. Loaded bkcl directly on server, no errors, with totally same env, just another different time...
3. Downloaded earlier backup, and loaded bkcl, same no errors.
4. Duplicated from server and loaded bkcl on my laptop, same.

---

I uploaded two debug log, the earlier one, when bkcl cannot be loaded, and another one when it now can be loaded without any error.
Should mention a difference, I removed GlowAPI, but was sure that wasn't the cause; tested on my laptop.
[debug.log](https://github.com/bergerhealer/BKCommonLib/files/11269181/debug.log)
[debug-earlier.log](https://github.com/bergerhealer/BKCommonLib/files/11269183/debug-earlier.log)

**Comment by bergerkiller** [comment]
Sounds like it failed randomly then, weird but not the first time it's happened. The earlier log is weird - but maybe I can figure something out that could cause the remapper to not be set at that point in time
