### ISSUE TITLE
Error: Failed to initialize net.minecraft.core.Holder field getHolder_invoker_3

### ISSUE THREAD

**Issue by ChrissW-R1** [bergerhealer/BKCommonLib#145]
##### Spigot version:

Paper 1.19.1-111

#### Problem or bug:

Get error on initialization: [BKCommonLib] Failed to initialize net.minecraft.core.Holder field getHolder_invoker_3
LightCleaner and TrainCarts couldn't use.

#### Expected behaviour:

Plugin works in 1.19.1

#### Steps to reproduce:

Enable BKCommonLib in Paper 1.19.1-111

#### Log
`
[17:35:02] [Server thread/INFO]: [BKCommonLib] Loading BKCommonLib v1.19.2-v1
[17:35:02] [Server thread/WARN]: [BKCommonLib] Since Minecraft 1.17 the server is obfuscated and requires the server mappings to interpret it correctly
[17:35:02] [Server thread/WARN]: [BKCommonLib] BKCommonLib will now download Minecraft 1.19.1 server mappings from Mojang's servers
[17:35:02] [Server thread/WARN]: [BKCommonLib] The file will be installed in: plugins/BKCommonLib/minecraft/1.19.1_server_mappings.txt
[17:35:02] [Server thread/WARN]: [BKCommonLib] By downloading these files you further agree with Mojang's EULA.
[17:35:02] [Server thread/WARN]: [BKCommonLib] The EULA can be read here: https://account.mojang.com/documents/minecraft_eula
[17:35:02] [Server thread/WARN]: [BKCommonLib] > Fetching JSON from Mojang servers: https://launchermeta.mojang.com/mc/game/version_manifest.json
[17:35:02] [Server thread/WARN]: [BKCommonLib] > Fetching JSON from Mojang servers: https://piston-meta.mojang.com/v1/packages/ae2cfa3c2dc55d5586a58757f5d4d75eb56b774c/1.19.1.json
[17:35:02] [Server thread/WARN]: [BKCommonLib] > Fetching Server Mappings from Mojang servers: https://piston-data.mojang.com/v1/objects/3565648cdd47ae15738fb804a95a659137d7cfd3/server.txt
[17:35:03] [Server thread/WARN]: [BKCommonLib] > Verifying Server Mappings...
[17:35:03] [Server thread/WARN]: [BKCommonLib] > Server Mappings verified, download completed!
[17:35:03] [Server thread/ERROR]: [BKCommonLib] Failed to compile method body ([source error] dimensionTypeRegistration() not found in net.minecraft.world.level.GeneratorAccessSeed):
[17:35:03] [Server thread/ERROR]: [BKCommonLib] public java.lang.Object getHolder(org.bukkit.craftbukkit.v1_19_R1.CraftWorld world) {
{
    return world.getHandle().dimensionTypeRegistration();
}
return null;}
[17:35:03] [Server thread/ERROR]: [BKCommonLib] Failed to initialize net.minecraft.core.Holder field getHolder_invoker_3
java.lang.RuntimeException: An exception occurred
Caused by: com.bergerkiller.mountiplex.dep.javassist.compiler.CompileError: dimensionTypeRegistration() not found in net.minecraft.world.level.GeneratorAccessSeed
	at com.bergerkiller.mountiplex.dep.javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:777) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.mountiplex.reflection.util.asm.javassist.MPLJvstTypeChecker.atCallExprSuppressLookup(MPLJvstTypeChecker.java:113) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.mountiplex.reflection.util.asm.javassist.MPLJvstTypeChecker.atCallExpr(MPLJvstTypeChecker.java:40) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.ast.CallExpr.accept(CallExpr.java:49) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:266) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.compileExpr(CodeGen.java:253) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atReturnStmnt2(CodeGen.java:689) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.JvstCodeGen.atReturnStmnt(JvstCodeGen.java:443) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atStmnt(CodeGen.java:393) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atStmnt(CodeGen.java:381) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atStmnt(CodeGen.java:381) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atMethodBody(CodeGen.java:321) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atMethodDecl(CodeGen.java:303) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.ast.MethodDecl.accept(MethodDecl.java:47) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.Javac.compileMethod(Javac.java:175) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.Javac.compile(Javac.java:102) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.mountiplex.reflection.util.asm.javassist.MPLCtNewMethod.make(MPLCtNewMethod.java:32) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker.makeMethodAndLog(GeneratedCodeInvoker.java:45) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker.create(GeneratedCodeInvoker.java:261) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.mountiplex.reflection.util.fast.InitInvoker$InitGeneratedCodeInvoker.create(InitInvoker.java:318) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.mountiplex.reflection.util.fast.InitInvoker.initializeInvoker(InitInvoker.java:75) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.mountiplex.reflection.util.fast.Invoker.forceInitialization(Invoker.java:25) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.mountiplex.reflection.declarations.Template$Class.forceInitialization(Template.java:191) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.bukkit.common.conversion.type.MC1_18_2_Conversion.init(MC1_18_2_Conversion.java:26) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.bukkit.common.internal.CommonBootstrap.initResolvers(CommonBootstrap.java:687) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.bukkit.common.internal.CommonBootstrap.initCommonServer(CommonBootstrap.java:210) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.bukkit.common.Common.<clinit>(Common.java:125) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.bukkit.common.internal.CommonPlugin.onLoad(CommonPlugin.java:504) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:427) ~[paper-1.19.1.jar:git-Paper-111]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:278) ~[paper-1.19.1.jar:git-Paper-111]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1124) ~[paper-1.19.1.jar:git-Paper-111]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-111]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:35:03] [Server thread/ERROR]: [BKCommonLib] An error occurred while loading
java.lang.ExceptionInInitializerError: null
	at com.bergerkiller.bukkit.common.internal.CommonPlugin.onLoad(CommonPlugin.java:504) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:427) ~[paper-1.19.1.jar:git-Paper-111]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:278) ~[paper-1.19.1.jar:git-Paper-111]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1124) ~[paper-1.19.1.jar:git-Paper-111]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-111]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Not all members of template for net.minecraft.core.Holder could be initialized!
	at com.bergerkiller.mountiplex.reflection.declarations.Template$Class.forceInitialization(Template.java:203) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.bukkit.common.conversion.type.MC1_18_2_Conversion.init(MC1_18_2_Conversion.java:26) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.bukkit.common.internal.CommonBootstrap.initResolvers(CommonBootstrap.java:687) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.bukkit.common.internal.CommonBootstrap.initCommonServer(CommonBootstrap.java:210) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.bukkit.common.Common.<clinit>(Common.java:125) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	... 6 more
`

**Comment by bergerkiller** [comment]
Im puzzled why CraftWorld.getHandle() is returning a net.minecraft.world.level.GeneratorAccessSeed type. This makes no sense at all. Is there any plugin on the server that does remapping or is dubbed "makes old plugins work" or something?

**Comment by bergerkiller** [comment]
Actually, this might just be a confusion from javassist itself in the error message, ServerLevel does implement GeneratorAccessSeed. For now do check whether updating paper to a newer build of 1.19.1 (if this exists) helps.

**Comment by bergerkiller** [comment]
Hm yeah, strange. Im starting to think a simple server restart might just fix it. No issue on my end but it might be a random-ish situation with the remapper

**Comment by ChrissW-R1** [comment]
> Actually, this might just be a confusion from javassist itself in the error message, ServerLevel does implement GeneratorAccessSeed. For now do check whether updating paper to a newer build of 1.19.1 (if this exists) helps.

Unfortunately there is no new version.


> Hm yeah, strange. Im starting to think a simple server restart might just fix it. No issue on my end but it might be a random-ish situation with the remapper

Yes, it is very weird. I had restarted the server many times, but the error occurs again. Now I added a new plugin and the issue disappeard. So never mind. I will come back, if the issue returns **and** is reproducable.
