### ISSUE TITLE
Error on 1.8.8 server startup

### ISSUE THREAD

**Issue by HowardZHY** [bergerhealer/BKCommonLib#149]
##### BkCommonLib version:
latest from jenkins
##### Spigot version:
BurritoSpigot 1.8.8
<hr>

#### Problem or bug:
[01:05:24 INFO]: [BKCommonLib] Enabling BKCommonLib v1.19.2-v4-SNAPSHOT
[01:05:24 INFO]: [BKCommonLib] BKCommonLib is running on Spigot (git-BurritoSpigot-"700f01e") : v1_8_R3 (Minecraft 1.8.8)
[01:05:24 INFO]: Now using the ProtocolLib library to provide Packet Listener and Monitor support
[01:05:24 ERROR]: Failed to enable component '[1.8 AND LATER]' of BKCommonLib.BlockDataWrapperHook
java.lang.UnsupportedOperationException: Values field is of type interface java.util.Map, expected class com.google.common.collect.ImmutableMap
        at com.bergerkiller.bukkit.common.internal.logic.BlockDataWrapperHook_Impl.baseEnable(BlockDataWrapperHook_Impl.java:64) ~[BKCommonLib-1.19.2-v4-SNAPSHOT-1421.jar:?]
        at com.bergerkiller.bukkit.common.internal.logic.BlockDataWrapperHook.enable(BlockDataWrapperHook.java:92) ~[BKCommonLib-1.19.2-v4-SNAPSHOT-1421.jar:?]
        at com.bergerkiller.bukkit.common.component.LibraryComponentHolder.tryCreateAndEnableComponent(LibraryComponentHolder.java:110) [BKCommonLib-1.19.2-v4-SNAPSHOT-1421.jar:?]
        at com.bergerkiller.bukkit.common.component.LibraryComponentSelector.update(LibraryComponentSelector.java:275) [BKCommonLib-1.19.2-v4-SNAPSHOT-1421.jar:?]
        at com.bergerkiller.bukkit.common.internal.logic.BlockDataWrapperHook.<clinit>(BlockDataWrapperHook.java:23) [BKCommonLib-1.19.2-v4-SNAPSHOT-1421.jar:?]
        at com.bergerkiller.bukkit.common.internal.CommonPlugin.enable(CommonPlugin.java:686) [BKCommonLib-1.19.2-v4-SNAPSHOT-1421.jar:?]
        at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:845) [BKCommonLib-1.19.2-v4-SNAPSHOT-1421.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [BurritoSpigot.jar:git-BurritoSpigot-"700f01e"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [BurritoSpigot.jar:git-BurritoSpigot-"700f01e"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [BurritoSpigot.jar:git-BurritoSpigot-"700f01e"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [BurritoSpigot.jar:git-BurritoSpigot-"700f01e"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [BurritoSpigot.jar:git-BurritoSpigot-"700f01e"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:203) [BurritoSpigot.jar:git-BurritoSpigot-"700f01e"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [BurritoSpigot.jar:git-BurritoSpigot-"700f01e"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]

**Comment by bergerkiller** [comment]
On BurritoSpigot* that is. I wonder why they changed from ImmutableMap to a Map for that field. Error shouldnt cause any problems if it loads the fallback at least, as its just an optimization which fails.

**Comment by bergerkiller** [comment]
![ScreenShot 2022-11-25 18 51 21](https://user-images.githubusercontent.com/957601/204035645-2ad96f33-a3ed-45cc-b5a4-b5a5b2de849e.jpg)
ahaa...

**Comment by bergerkiller** [comment]
Try with this one https://ci.mg-dev.eu/job/BKCommonLib/1422/

**Comment by HowardZHY** [comment]
thx
