### ISSUE TITLE
BKCommonLib vomits error on startup

### ISSUE THREAD

**Issue by professorparabellum** [bergerhealer/BKCommonLib#152]
##### Spigot version: 1.12.2

<hr>

#### Problem or bug:
Spits out this error on startup:
```
[14:49:42 WARN]: [BKCommonLib] Field 'data' not found in template for net.minecraft.nbt.NBTTagCompound
[14:49:42 ERROR]: [BKCommonLib] Failed to initialize net.minecraft.nbt.NBTTagCompound net.minecraft.nbt.NBTTagCompound.data
java.lang.UnsupportedOperationException: Field net.minecraft.nbt.NBTTagCompound.data is not available
	at com.bergerkiller.mountiplex.reflection.util.FastField.checkInit(FastField.java:63) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.util.FastField$FastFieldInitProxy.read(FastField.java:214) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.util.FastField$FastFieldInitProxy.checkCanRead(FastField.java:276) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.util.FastField.forceInitialization(FastField.java:148) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.declarations.Template$AbstractField.forceInitialization(Template.java:733) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.declarations.Template$AbstractFieldConverter.forceInitialization(Template.java:863) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.declarations.Template$Class.forceInitialization(Template.java:168) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonBootstrap.preloadCriticalComponents(CommonBootstrap.java:802) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonPlugin.enable(CommonPlugin.java:575) ~[?:?]
	at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:845) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[dionysus-1.12.2.jar:git-Dionysus-"040c353"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[dionysus-1.12.2.jar:git-Dionysus-"040c353"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[dionysus-1.12.2.jar:git-Dionysus-"040c353"]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:393) ~[dionysus-1.12.2.jar:git-Dionysus-"040c353"]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:342) ~[dionysus-1.12.2.jar:git-Dionysus-"040c353"]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:229) ~[dionysus-1.12.2.jar:git-Dionysus-"040c353"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:635) ~[dionysus-1.12.2.jar:git-Dionysus-"040c353"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:49:42 ERROR]: [BKCommonLib.Reflection] Failed to initialize some critical components
java.lang.IllegalStateException: Not all members of template for net.minecraft.nbt.NBTTagCompound could be initialized!
	at com.bergerkiller.mountiplex.reflection.declarations.Template$Class.forceInitialization(Template.java:203) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonBootstrap.preloadCriticalComponents(CommonBootstrap.java:802) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonPlugin.enable(CommonPlugin.java:575) ~[?:?]
	at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:845) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[dionysus-1.12.2.jar:git-Dionysus-"040c353"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[dionysus-1.12.2.jar:git-Dionysus-"040c353"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[dionysus-1.12.2.jar:git-Dionysus-"040c353"]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:393) ~[dionysus-1.12.2.jar:git-Dionysus-"040c353"]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:342) ~[dionysus-1.12.2.jar:git-Dionysus-"040c353"]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:229) ~[dionysus-1.12.2.jar:git-Dionysus-"040c353"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:635) ~[dionysus-1.12.2.jar:git-Dionysus-"040c353"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

#### Expected behaviour:
Clean Console , plugin works i just dont like to see the error

#### Steps to reproduce:
- Use Dionysus 1.12.2
- Use JDK 17
- Install BKCommonLib

**Comment by bergerkiller** [comment]
First time I heard of Dionysus, I assume it just isnt supported (yet)

**Comment by professorparabellum** [comment]
Works fine on paper 1.12.2, i assume its just a jdk17 issue.

**Comment by bergerkiller** [comment]
Well, no. The error you posted indicates Dionysus renamed, removed or otherwise changed a field in the NBTTagCompound class. Not JDK related.

**Comment by professorparabellum** [comment]
[17:17:13 WARN]: [BKCommonLib] A class member of net.minecraft.nbt.NBTTagCompound was not found!
[17:17:13 WARN]: [BKCommonLib] Failed to find field private final (Map<String, NBTBaseHandle>) Map<String, NBTBase> data:map; - Alternatives:
[17:17:13 WARN]: [BKCommonLib]   - public final net.minecraft.server.v1_12_R1.NBTTagCompound.CustomObject2ObjectOpenHashMap<String, net.minecraft.server.v1_12_R1.NBTBase> map;
[17:17:13 WARN]: [BKCommonLib]   - private int cachedSize;
[17:17:13 WARN]: [BKCommonLib]   - private static final org.apache.logging.log4j.Logger b;
[17:17:13 WARN]: [BKCommonLib]   - private static final regex.Pattern c;

**Comment by professorparabellum** [comment]
net.minecraft.nbt does not exist in 1.12.2, which is strange...it exists in 1.13+ if i remember correctly

**Comment by professorparabellum** [comment]
I think these patches are to blame:
0183-Reaper-0098-cache-chunk-NBT-in-the-PacketPlayOutMapC
0037-Don-t-process-nbt-thats-too-big
