### ISSUE TITLE
Incorrect state: no controller assigned!

### ISSUE THREAD

**Issue by MrCreepyCraft32** [bergerhealer/BKCommonLib#164]
##### Spigot version: git-Paper-485 (MC: 1.20.4)

<hr>

#### Problem or bug:
```
[01:09:36 ERROR]: [BKCommonLib.Debug] Incorrect state: no controller assigned! Creator:  -  BKCommonLib-1.20.4-v4-1691.jar//com.bergerkiller.bukkit.common.internal.hooks.EntityHook.checkController(EntityHook.java:616)
java.lang.Throwable: null
        at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.getStack(EntityHook.java:56) ~[BKCommonLib-1.20.4-v4-1691.jar:?]
        at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.checkController(EntityHook.java:616) ~[BKCommonLib-1.20.4-v4-1691.jar:?]
        at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.onPush(EntityHook.java:215) ~[BKCommonLib-1.20.4-v4-1691.jar:?]
        at com.bergerkiller.bukkit.common.controller.EntityController.onPush(EntityController.java:157) ~[BKCommonLib-1.20.4-v4-1691.jar:?]
        at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.onPushWithEntity(EntityHook.java:233) ~[BKCommonLib-1.20.4-v4-1691.jar:?]
        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mpldefgen7b61776a.invokeVA(Unknown Source) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.util.fast.InitInvoker.invokeVA(InitInvoker.java:113) ~[BKCommonLib-1.20.4-v4-1691.jar:?]
        at com.bergerkiller.mountiplex.reflection.ClassInterceptor$CallbackMethodInterceptor.invokeVA(ClassInterceptor.java:523) ~[BKCommonLib-1.20.4-v4-1691.jar:?]
        at com.bergerkiller.mountiplex.reflection.util.fast.Invoker.invoke(Invoker.java:45) ~[BKCommonLib-1.20.4-v4-1691.jar:?]
        at net.minecraft.world.entity.vehicle.EntityMinecartRideable$mpldefgen1c5402c6.push(Unknown Source) ~[?:?]
        at net.minecraft.world.entity.Entity.push(Entity.java:2163) ~[paper-1.20.4.jar:git-Paper-485]
        at net.minecraft.world.entity.vehicle.AbstractMinecart.push(AbstractMinecart.java:862) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mpldefgen43327294.invoke(Unknown Source) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method$Converted.invoke(Template.java:1653) ~[BKCommonLib-1.20.4-v4-1691.jar:?]
        at com.bergerkiller.generated.net.minecraft.world.entity.EntityHandle$impl.collide(Unknown Source) ~[?:?]
        at com.bergerkiller.bukkit.common.utils.EntityUtil.doCollision(EntityUtil.java:126) ~[BKCommonLib-1.20.4-v4-1691.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartMember.onPhysicsPostMove(MinecartMember.java:2474) ~[TrainCarts-1.20.4-v2-1556.jar:?]
        at com.bergerkiller.bukkit.tc.controller.type.MinecartMemberRideable.onPhysicsPostMove(MinecartMemberRideable.java:111) ~[TrainCarts-1.20.4-v2-1556.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics_step(MinecartGroup.java:2077) ~[TrainCarts-1.20.4-v2-1556.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics(MinecartGroup.java:1879) ~[TrainCarts-1.20.4-v2-1556.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroupStore.doFixedTick(MinecartGroupStore.java:40) ~[TrainCarts-1.20.4-v2-1556.jar:?]
        at com.bergerkiller.bukkit.tc.controller.global.TrainUpdateController$TrainUpdateTask.run(TrainUpdateController.java:225) ~[TrainCarts-1.20.4-v2-1556.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-485]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-485]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142) ~[paper-1.20.4.jar:git-Paper-485]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-485]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[01:09:36 ERROR]: [BKCommonLib] An unhandled exception occurred during the entity push callback
java.lang.NullPointerException: Cannot invoke "com.bergerkiller.bukkit.common.internal.hooks.EntityHook.onPush(double, double, double)" because "this.base" is null
        at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.onPush(EntityHook.java:218) ~[BKCommonLib-1.20.4-v4-1691.jar:?]
        at com.bergerkiller.bukkit.common.controller.EntityController.onPush(EntityController.java:157) ~[BKCommonLib-1.20.4-v4-1691.jar:?]
        at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.onPushWithEntity(EntityHook.java:233) ~[BKCommonLib-1.20.4-v4-1691.jar:?]
        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mpldefgen7b61776a.invokeVA(Unknown Source) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.util.fast.InitInvoker.invokeVA(InitInvoker.java:113) ~[BKCommonLib-1.20.4-v4-1691.jar:?]
        at com.bergerkiller.mountiplex.reflection.ClassInterceptor$CallbackMethodInterceptor.invokeVA(ClassInterceptor.java:523) ~[BKCommonLib-1.20.4-v4-1691.jar:?]
        at com.bergerkiller.mountiplex.reflection.util.fast.Invoker.invoke(Invoker.java:45) ~[BKCommonLib-1.20.4-v4-1691.jar:?]
        at net.minecraft.world.entity.vehicle.EntityMinecartRideable$mpldefgen1c5402c6.push(Unknown Source) ~[?:?]
        at net.minecraft.world.entity.Entity.push(Entity.java:2163) ~[paper-1.20.4.jar:git-Paper-485]
        at net.minecraft.world.entity.vehicle.AbstractMinecart.push(AbstractMinecart.java:862) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mpldefgen43327294.invoke(Unknown Source) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method$Converted.invoke(Template.java:1653) ~[BKCommonLib-1.20.4-v4-1691.jar:?]
        at com.bergerkiller.generated.net.minecraft.world.entity.EntityHandle$impl.collide(Unknown Source) ~[?:?]
        at com.bergerkiller.bukkit.common.utils.EntityUtil.doCollision(EntityUtil.java:126) ~[BKCommonLib-1.20.4-v4-1691.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartMember.onPhysicsPostMove(MinecartMember.java:2474) ~[TrainCarts-1.20.4-v2-1556.jar:?]
        at com.bergerkiller.bukkit.tc.controller.type.MinecartMemberRideable.onPhysicsPostMove(MinecartMemberRideable.java:111) ~[TrainCarts-1.20.4-v2-1556.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics_step(MinecartGroup.java:2077) ~[TrainCarts-1.20.4-v2-1556.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics(MinecartGroup.java:1879) ~[TrainCarts-1.20.4-v2-1556.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroupStore.doFixedTick(MinecartGroupStore.java:40) ~[TrainCarts-1.20.4-v2-1556.jar:?]
        at com.bergerkiller.bukkit.tc.controller.global.TrainUpdateController$TrainUpdateTask.run(TrainUpdateController.java:225) ~[TrainCarts-1.20.4-v2-1556.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-485]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-485]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142) ~[paper-1.20.4.jar:git-Paper-485]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-485]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

#### Expected behaviour:
No errors at startup

#### Steps to reproduce:
Start the server

#### Additional information:
I'm using Train_Carts version 1.20.4-v2

**Comment by bergerkiller** [comment]
Its related to a broken onPush callback, I guess. An error probably brought it out of sync or something. Probably once I fix that issue this one will be fixed too.
