### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by Vlader97** [bergerhealer/BKCommonLib#165]
##### Paper version: 1.20.1 build196

<hr>

#### Problem or bug: 
Sometimes this error appears in the console. 

`[Server thread/ERROR]: [BKCommonLib] An unhandled exception occurred during the entity push callback
java.lang.NullPointerException: Cannot invoke "com.bergerkiller.bukkit.common.internal.hooks.EntityHook.onPush(double, double, double)" because "this.base" is null
	at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.onPush(EntityHook.java:218) ~[BKCommonLib-1.20.4-v4-1691.jar:?]
	at com.bergerkiller.bukkit.common.controller.EntityController.onPush(EntityController.java:157) ~[BKCommonLib-1.20.4-v4-1691.jar:?]
	at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.onPushWithEntity(EntityHook.java:233) ~[BKCommonLib-1.20.4-v4-1691.jar:?]
	at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mpldefgen6fd74758.invokeVA(Unknown Source) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.ClassInterceptor$CallbackMethodInterceptor.invokeVA(ClassInterceptor.java:523) ~[BKCommonLib-1.20.4-v4-1691.jar:?]
	at com.bergerkiller.mountiplex.reflection.util.fast.Invoker.invoke(Invoker.java:45) ~[BKCommonLib-1.20.4-v4-1691.jar:?]
	at net.minecraft.world.entity.vehicle.EntityMinecartRideable$mpldefgen386b720d.push(Unknown Source) ~[?:?]
	at net.minecraft.world.entity.Entity.push(Entity.java:2129) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.world.entity.vehicle.AbstractMinecart.push(AbstractMinecart.java:901) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mpldefgen72b95eb3.invoke(Unknown Source) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.declarations.Template$Method$Converted.invoke(Template.java:1653) ~[BKCommonLib-1.20.4-v4-1691.jar:?]
	at com.bergerkiller.generated.net.minecraft.world.entity.EntityHandle$impl.collide(Unknown Source) ~[?:?]
	at com.bergerkiller.bukkit.common.utils.EntityUtil.doCollision(EntityUtil.java:126) ~[BKCommonLib-1.20.4-v4-1691.jar:?]
	at com.bergerkiller.bukkit.tc.controller.MinecartMember.onPhysicsPostMove(MinecartMember.java:2474) ~[TrainCarts-1.20.4-v2-1556.jar:?]
	at com.bergerkiller.bukkit.tc.controller.type.MinecartMemberRideable.onPhysicsPostMove(MinecartMemberRideable.java:111) ~[TrainCarts-1.20.4-v2-1556.jar:?]
	at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics_step(MinecartGroup.java:2077) ~[TrainCarts-1.20.4-v2-1556.jar:?]
	at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics(MinecartGroup.java:1879) ~[TrainCarts-1.20.4-v2-1556.jar:?]
	at com.bergerkiller.bukkit.tc.controller.MinecartGroupStore.doFixedTick(MinecartGroupStore.java:40) ~[TrainCarts-1.20.4-v2-1556.jar:?]
	at com.bergerkiller.bukkit.tc.controller.global.TrainUpdateController$TrainUpdateTask.run(TrainUpdateController.java:225) ~[TrainCarts-1.20.4-v2-1556.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1479) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
`

I have these plugins on the server if it helps with the solution:
TrainCarts-1.20.4-v2-1556
MyWorlds-1.20.4-v3-268
LightCleaner-1.19.3-v1-149

#### Expected behaviour: 
No error

#### Steps to reproduce:
It happens randomly

**Comment by Bevan0** [comment]
Looks like the same as #164.

**Comment by bergerkiller** [comment]
This should be better now https://ci.mg-dev.eu/job/BKCommonLib/1710/
