### ISSUE TITLE
#21 for BKCommonLib v1.20.6-v1-SNAPSHOT generated an exception

### ISSUE THREAD

**Issue by ChosenCraftMC** [bergerhealer/BKCommonLib#167]
##### BkCommonLib version:
 BKCommonLib v1.20.6-v1-SNAPSHOT generated an exception
##### Spigot version:
1.20.6
<hr>

#### Problem or bug:
28.05 19:45:48 [Server] WARN Task #21 for BKCommonLib v1.20.6-v1-SNAPSHOT generated an exception
28.05 19:45:48 [Server] INFO java.lang.NoClassDefFoundError: com/bergerkiller/mountiplex/reflection/util/fast/GeneratedCodeInvoker$mpldefgen5652fd68
28.05 19:45:48 [Server] INFO at com.bergerkiller.generated.net.minecraft.world.entity.decoration.EntityItemFrameHandle$impl.getBukkitWorld(Unknown Source) ~[?:?]
28.05 19:45:48 [Server] INFO at BKCommonLib-1.20.6-v1-SNAPSHOT-1742.jar/com.bergerkiller.bukkit.common.internal.map.ItemFrameClusterKey.<init>(ItemFrameClusterKey.java:19) ~[BKCommonLib-1.20.6-v1-SNAPSHOT-1742.jar:?]
28.05 19:45:48 [Server] INFO at BKCommonLib-1.20.6-v1-SNAPSHOT-1742.jar/com.bergerkiller.bukkit.common.internal.map.CommonMapController$ByWorldItemFrameSetRefresher.run(CommonMapController.java:1529) ~[BKCommonLib-1.20.6-v1-SNAPSHOT-1742.jar:?]
28.05 19:45:48 [Server] INFO at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
28.05 19:45:48 [Server] INFO at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
28.05 19:45:48 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1699) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
28.05 19:45:48 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
28.05 19:45:48 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
28.05 19:45:48 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
28.05 19:45:48 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
28.05 19:45:48 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
28.05 19:45:48 [Server] INFO Caused by: java.lang.NoClassDefFoundError: com/bergerkiller/mountiplex/reflection/util/asm/MPLType$LoaderClosedException

**Comment by bergerkiller** [comment]
LoaderClosedException usually occurs when theres some other plugin that fails to enable, disables itself, and bugs out paper somehow. That, or /reload

**Comment by ChosenCraftMC** [comment]
Hmmm it could be a plugin issue we have a few "Broken" ones which i think is due to them all not being 1.20.6 but im still investigating. Would any of these cause issue, These are the ones that are currently showing in red in our /pl list which i thought usually means there is a issue MarriageMaster, Excellent Crates, Excellent Enchants, MCPets, PlayerWarps, Show Item, TabList, Vulcan, and zAuctionHouse

**Comment by bergerkiller** [comment]
Its kind of a strange bug, in the past it seemd any random plugin can cause it. Ive seen protocollib cause it for example, with no obvious route to it. I did make a small patch to bkcommonlib to change how it did worldedit detection as this bug frequently occurred there, but the real bug is still elsewhere.
