### ISSUE TITLE
Warnings and errors in version 1.21

### ISSUE THREAD

**Issue by mjl1010** [bergerhealer/BKCommonLib#169]
##### BkCommonLib version:
v1.21-v1-SNAPSHOT-1750
##### Spigot version:
(Paper) 1.21-37-master (Implementing API version 1.21-R0.1-SNAPSHOT)

<hr>

#### Problem or bug:
I see a lot of warnings and errors. See the log:
```
[21:29:19] [Server thread/INFO]: [BKCommonLib] Loading server plugin BKCommonLib v1.21-v1-SNAPSHOT
[21:29:21] [Server thread/WARN]: [BKCommonLib] Requirement was not found in net.minecraft.server.level.LightEngineThreaded:
[21:29:21] [Server thread/WARN]: [BKCommonLib] Failed to find field private final net.minecraft.util.thread.ThreadedMailbox<Runnable> taskMailbox:b; - Alternatives:
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - private final ChunkMap chunkMap;
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - private final int taskPerBatch;
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - private final concurrent.atomic.AtomicLong chunkWorkCounter;
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - protected final net.minecraft.world.level.LevelHeightAccessor levelHeightAccessor;
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - protected final ca.spottedleaf.moonrise.patches.starlight.light.StarLightInterface lightEngine;
[21:29:21] [Server thread/WARN]: [BKCommonLib] Requirement was not found in net.minecraft.server.level.WorldServer:
[21:29:21] [Server thread/WARN]: [BKCommonLib] Failed to find field private final net.minecraft.world.level.entity.PersistentEntitySectionManager entityManager; - Alternatives:
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - private org.spigotmc.TickLimiter entityLimiter;
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - private final net.minecraft.world.level.biome.BiomeManager biomeManager;
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - private final net.minecraft.world.level.StructureManager structureManager;
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - private final ca.spottedleaf.moonrise.patches.chunk_system.io.datacontroller.EntityDataController entityDataController;
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - private ca.spottedleaf.moonrise.patches.chunk_system.level.entity.EntityLookup entityLookup;
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - private final alternate.current.wire.WireHandler wireHandler;
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - public final net.minecraft.world.level.storage.LevelStorageSource.LevelStorageAccess convertable;
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - private final net.minecraft.world.level.gameevent.GameEventDispatcher gameEventDispatcher;
[21:29:21] [Server thread/ERROR]: [BKCommonLib.Reflection] Failed to initialize WorldServer entityManager field: entityManager
java.lang.NoSuchFieldException: entityManager
	at java.base/java.lang.Class.getDeclaredField(Class.java:2782) ~[?:?]
	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredField(AbstractDefaultRulesReflectionProxy.java:90) ~[reflection-rewriter-runtime-0.0.3.jar:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredField(Unknown Source) ~[paper-1.21.jar:1.21-37-dd49fba]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.internal.logic.EntityAddRemoveHandler_1_17.<init>(EntityAddRemoveHandler_1_17.java:82) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.component.LibraryComponent.lambda$forVersions$1(LibraryComponent.java:142) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.component.LibraryComponent$2.create(LibraryComponent.java:213) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.component.LibraryComponentHolder.tryCreateAndEnableComponent(LibraryComponentHolder.java:100) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.component.LibraryComponentSelector.update(LibraryComponentSelector.java:266) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.internal.logic.EntityAddRemoveHandler.<clinit>(EntityAddRemoveHandler.java:53) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68) ~[reflection-rewriter-runtime-0.0.3.jar:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source) ~[paper-1.21.jar:1.21-37-dd49fba]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.Common.loadClasses(Common.java:173) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.internal.CommonClasses.loadCommon(CommonClasses.java:86) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.internal.CommonClasses.loadLogic(CommonClasses.java:72) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.internal.CommonClasses.init(CommonClasses.java:56) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.internal.CommonPlugin.onLoad(CommonPlugin.java:548) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.21.jar:1.21-37-dd49fba]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.21.jar:1.21-37-dd49fba]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.21.jar:1.21-37-dd49fba]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.jar:1.21-37-dd49fba]
	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:535) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:290) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-37-dd49fba]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[21:29:21] [Server thread/WARN]: [BKCommonLib] Requirement was not found in net.minecraft.server.level.WorldServer:
[21:29:21] [Server thread/WARN]: [BKCommonLib] Failed to find field public final net.minecraft.world.level.entity.PersistentEntitySectionManager entityManager; - Alternatives:
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - public final net.minecraft.world.level.storage.LevelStorageSource.LevelStorageAccess convertable;
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - public boolean hasEntityMoveEvent;
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - public final co.aikar.timings.WorldTimingsHandler timings;
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - public int wakeupInactiveRemainingVillagers;
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - public final ServerChunkCache chunkSource;
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - public int wakeupInactiveRemainingMonsters;
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - public boolean preventPoiUpdated;
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - private org.spigotmc.TickLimiter entityLimiter;
[21:29:21] [Server thread/WARN]: [BKCommonLib] Requirement was not found in net.minecraft.server.level.WorldServer:
[21:29:21] [Server thread/WARN]: [BKCommonLib] Failed to find field private final net.minecraft.world.level.entity.PersistentEntitySectionManager entityManager; - Alternatives:
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - private org.spigotmc.TickLimiter entityLimiter;
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - private final net.minecraft.world.level.biome.BiomeManager biomeManager;
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - private final net.minecraft.world.level.StructureManager structureManager;
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - private final ca.spottedleaf.moonrise.patches.chunk_system.io.datacontroller.EntityDataController entityDataController;
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - private ca.spottedleaf.moonrise.patches.chunk_system.level.entity.EntityLookup entityLookup;
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - private final alternate.current.wire.WireHandler wireHandler;
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - public final net.minecraft.world.level.storage.LevelStorageSource.LevelStorageAccess convertable;
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - private final net.minecraft.world.level.gameevent.GameEventDispatcher gameEventDispatcher;
[21:29:21] [Server thread/WARN]: [BKCommonLib] Requirement was not found in net.minecraft.world.level.entity.EntityTickList:
[21:29:21] [Server thread/WARN]: [BKCommonLib] Failed to find field private it.unimi.dsi.fastutil.ints.Int2ObjectMap<Entity> active; - Alternatives:
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - private final ca.spottedleaf.moonrise.common.list.IteratorSafeOrderedReferenceSet<Entity> entities;
[21:29:21] [Server thread/WARN]: [BKCommonLib] Requirement was not found in net.minecraft.world.level.entity.EntityTickList:
[21:29:21] [Server thread/WARN]: [BKCommonLib] Failed to find field private it.unimi.dsi.fastutil.ints.Int2ObjectMap<Entity> passive; - Alternatives:
[21:29:21] [Server thread/WARN]: [BKCommonLib]   - private final ca.spottedleaf.moonrise.common.list.IteratorSafeOrderedReferenceSet<Entity> entities;
[21:29:22] [Server thread/WARN]: [BKCommonLib] Requirement was not found in net.minecraft.world.level.chunk.storage.IChunkLoader:
[21:29:22] [Server thread/WARN]: [BKCommonLib] Failed to find field private final net.minecraft.world.level.chunk.storage.IOWorker ioworker:worker; - Alternatives:
[21:29:22] [Server thread/WARN]: [BKCommonLib]   - private final RegionFileStorage storage;
[21:29:22] [Server thread/WARN]: [BKCommonLib]   - private volatile net.minecraft.world.level.levelgen.structure.LegacyStructureDataHandler legacyStructureHandler;
[21:29:22] [Server thread/WARN]: [BKCommonLib]   - protected final com.mojang.datafixers.DataFixer fixerUpper;
[21:29:22] [Server thread/WARN]: [BKCommonLib] Requirement was not found in net.minecraft.world.level.chunk.storage.RegionFileSection:
[21:29:22] [Server thread/WARN]: [BKCommonLib] Failed to find field private final SimpleRegionStorage simpleRegionStorage; - Alternatives:
[21:29:22] [Server thread/WARN]: [BKCommonLib]   - private final RegionFileStorage regionStorage;
[21:29:22] [Server thread/WARN]: [BKCommonLib]   - private final net.minecraft.core.RegistryAccess registryAccess;
[21:29:22] [Server thread/WARN]: [BKCommonLib]   - private final ChunkIOErrorReporter errorReporter;
[21:29:22] [Server thread/WARN]: [BKCommonLib]   - private final it.unimi.dsi.fastutil.longs.LongLinkedOpenHashSet dirty;
[21:29:22] [Server thread/WARN]: [BKCommonLib]   - private final Long2ObjectMap<Optional<R>> storage;
[21:29:22] [Server thread/WARN]: [BKCommonLib]   - private final function.Function<Runnable, R> factory;
[21:29:22] [Server thread/WARN]: [BKCommonLib]   - private final function.Function<Runnable, com.mojang.serialization.Codec<R>> codec;
[21:29:22] [Server thread/WARN]: [BKCommonLib]   - protected final net.minecraft.world.level.LevelHeightAccessor levelHeightAccessor;
[21:29:28] [Server thread/INFO]: [BKCommonLib] Enabling BKCommonLib v1.21-v1-SNAPSHOT
[21:29:28] [Server thread/INFO]: [BKCommonLib] BKCommonLib is running on Paper (1.21-37-dd49fba | mojmap) : (Unknown) (Minecraft 1.21)
[21:29:28] [Server thread/INFO]: [BKCommonLib.Network] Now using the ProtocolLib library to provide Packet Listener and Monitor support
[21:29:29] [Server thread/INFO]: [BKCommonLib] [RegionChangeTracker] Region block changes will be notified from WorldEdit (>= v7.0.0)
[21:29:29] [Server thread/INFO]: [BKCommonLib] I don't make mistakes. I just find ways not to code this plugin.
[21:29:29] [Server thread/INFO]: [BKCommonLib] BKCommonLib version 1.21-v1-SNAPSHOT (build: 1750) enabled! (1.366s)
[21:29:30] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[21:29:30] [Server thread/INFO]: Time elapsed: 4 ms
[21:29:30] [Server thread/ERROR]: Could not pass event WorldLoadEvent to BKCommonLib v1.21-v1-SNAPSHOT
java.lang.UnsupportedOperationException: Field entityManager is not available
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.mountiplex.reflection.util.FastField.checkInit(FastField.java:63) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.mountiplex.reflection.util.FastField$FastFieldInitProxy.read(FastField.java:214) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.mountiplex.reflection.util.FastField$FastFieldInitProxy.get(FastField.java:280) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.mountiplex.reflection.util.FastField.get(FastField.java:168) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.internal.logic.EntityAddRemoveHandler_1_17.hook(EntityAddRemoveHandler_1_17.java:156) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.internal.logic.EntityAddRemoveHandler.onWorldEnabled(EntityAddRemoveHandler.java:99) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.internal.CommonListener.onWorldLoad(CommonListener.java:123) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-37-dd49fba]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-37-dd49fba]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-37-dd49fba]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:673) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-37-dd49fba]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[21:29:30] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[21:29:30] [Server thread/INFO]: Time elapsed: 0 ms
[21:29:30] [Server thread/ERROR]: Could not pass event WorldLoadEvent to BKCommonLib v1.21-v1-SNAPSHOT
java.lang.UnsupportedOperationException: Field entityManager is not available
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.mountiplex.reflection.util.FastField.checkInit(FastField.java:63) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.mountiplex.reflection.util.FastField$FastFieldInitProxy.read(FastField.java:214) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.mountiplex.reflection.util.FastField$FastFieldInitProxy.get(FastField.java:280) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.mountiplex.reflection.util.FastField.get(FastField.java:168) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.internal.logic.EntityAddRemoveHandler_1_17.hook(EntityAddRemoveHandler_1_17.java:156) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.internal.logic.EntityAddRemoveHandler.onWorldEnabled(EntityAddRemoveHandler.java:99) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.internal.CommonListener.onWorldLoad(CommonListener.java:123) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-37-dd49fba]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-37-dd49fba]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-37-dd49fba]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:673) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-37-dd49fba]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[21:29:30] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[21:29:30] [Server thread/INFO]: Time elapsed: 0 ms
[21:29:30] [Server thread/ERROR]: Could not pass event WorldLoadEvent to BKCommonLib v1.21-v1-SNAPSHOT
java.lang.UnsupportedOperationException: Field entityManager is not available
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.mountiplex.reflection.util.FastField.checkInit(FastField.java:63) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.mountiplex.reflection.util.FastField$FastFieldInitProxy.read(FastField.java:214) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.mountiplex.reflection.util.FastField$FastFieldInitProxy.get(FastField.java:280) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.mountiplex.reflection.util.FastField.get(FastField.java:168) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.internal.logic.EntityAddRemoveHandler_1_17.hook(EntityAddRemoveHandler_1_17.java:156) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.internal.logic.EntityAddRemoveHandler.onWorldEnabled(EntityAddRemoveHandler.java:99) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.internal.CommonListener.onWorldLoad(CommonListener.java:123) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-37-dd49fba]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-37-dd49fba]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-37-dd49fba]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:673) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-37-dd49fba]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
And 3 more times, just before done:
```
[21:29:47] [Server thread/ERROR]: [BKCommonLib] An error occurred in next-tick task 'com.bergerkiller.bukkit.common.internal.CommonListener$$Lambda/0x00007fc4fd48b800'
java.lang.UnsupportedOperationException: Field entityManager is not available
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.mountiplex.reflection.util.FastField.checkInit(FastField.java:63) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.mountiplex.reflection.util.FastField$FastFieldInitProxy.read(FastField.java:214) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.mountiplex.reflection.util.FastField$FastFieldInitProxy.get(FastField.java:280) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.mountiplex.reflection.util.FastField.get(FastField.java:168) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.internal.logic.EntityAddRemoveHandler_1_17.hook(EntityAddRemoveHandler_1_17.java:156) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.internal.logic.EntityAddRemoveHandler.onWorldEnabled(EntityAddRemoveHandler.java:99) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.internal.CommonPlugin.notifyWorldAdded(CommonPlugin.java:290) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.internal.CommonListener.lambda$onWorldInit$0(CommonListener.java:118) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.internal.CommonNextTickExecutor$ExecutorTask.run(CommonNextTickExecutor.java:161) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.21.jar:1.21-37-dd49fba]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1168) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-37-dd49fba]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
Apparently it works, but then the Train Carts don't work.

#### Expected behaviour:
No more warnings and errors in console :)
Thank you very much for the hard work.

#### Steps to reproduce:
Start a server with Paper 1.21 with this plugins: BKCommonLib, CommandHook, ChestShop, CMILib, dynmap, Elevator, Essentials, EssentialsChat, EssentialsSpawn, GSit, *iConomy, ItemEdit, *MySQLAPI, NBTAPI, NoPlugins, NoSpawnerChange, NoteBlockAPI, *PermissionsEx, ProtocolLib, Residence, SignLink, SimpleClans, SkinsRestorer, UltimateTimber, Vault, WorldEdit, ZeroTickStopper and (optional: TrainCarts).

**Comment by bergerkiller** [comment]
Try with https://ci.mg-dev.eu/job/BKCommonLib/1751/
