### ISSUE TITLE
Error on startup (Field 'f' does not exist)

### ISSUE THREAD

**Issue by MrPufferFish** [bergerhealer/BKCommonLib#19]
##### Spigot version: 1.9.2-R0.1-SNAPSHOT

The error below occour on startup.

<hr>
[18:12:38] [Server thread/INFO]: [BKCommonLib] Loading BKCommonLib v1.70-SNAPSHOT
[18:12:39] [Server thread/ERROR]: [BKCommonLib] [Reflection] Field 'f' does not exist in class file net.minecraft.server.v1_9_R1.PacketPlayInWindowClick (Update BKCommonLib?)
[18:12:39] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.internal.CommonPlugin.handleReflectionMissing(CommonPlugin.java:92)
[18:12:39] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.reflection.SafeField.load(SafeField.java:80)
[18:12:39] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.reflection.SafeField.<init>(SafeField.java:59)
[18:12:39] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.reflection.ClassTemplate.getField(ClassTemplate.java:253)
[18:12:39] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.protocol.PacketTypeClasses$NMSPacketPlayInWindowClick.<init>(PacketTypeClasses.java:902)
[18:12:39] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.protocol.PacketType.<clinit>(PacketType.java:137)
[18:12:39] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.reflection.classes.EntityTrackerRef.<clinit>(EntityTrackerRef.java:25)
[18:12:39] [Server thread/ERROR]: [BKCommonLib] at java.lang.Class.forName0(Native Method)
[18:12:39] [Server thread/ERROR]: [BKCommonLib] at java.lang.Class.forName(Class.java:264)
[18:12:39] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.Common.loadClasses(Common.java:118)
[18:12:39] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.internal.CommonClasses.loadCommon(CommonClasses.java:61)
[18:12:39] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.internal.CommonClasses.loadRef(CommonClasses.java:47)
[18:12:39] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.internal.CommonClasses.init(CommonClasses.java:21)
[18:12:39] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.internal.CommonPlugin.onLoad(CommonPlugin.java:308)
[18:12:39] [Server thread/ERROR]: [BKCommonLib] at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugins(CraftServer.java:301)
[18:12:39] [Server thread/ERROR]: [BKCommonLib] at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:201)
[18:12:39] [Server thread/ERROR]: [BKCommonLib] at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527)
[18:12:39] [Server thread/ERROR]: [BKCommonLib] at java.lang.Thread.run(Thread.java:745)
[18:12:39] [Server thread/WARN]: [BKCommonLib] Method void a(SoundEffect, BlockPosition) is not overrided in the World Listener!
[18:12:39] [Server thread/WARN]: [BKCommonLib] Method void a(World, BlockPosition, IBlockData, IBlockData, int) is not overrided in the World Listener!
[18:12:40] [Server thread/WARN]: [BKCommonLib] Entity Type 'LINGERING_POTION' is not registered as CommonEntityType

**Comment by FriwiDev** [comment]
Should be fixed now. Please try again.
