### ISSUE TITLE
Error on starting - Field 'f' does not exist

### ISSUE THREAD

**Issue by Catreina** [bergerhealer/BKCommonLib#21]
##### Spigot version:  1.9 R1  (1.9.2)

<hr>

#### Problem or bug:
[02:27:19 INFO]: [BKCommonLib] Loading BKCommonLib v1.70-SNAPSHOT
[02:27:19 ERROR]: [BKCommonLib] [Reflection] Field 'f' does not exist in class file net.minecraft.server.v1_9_R1.PacketPlayInWindowClick (Update BKCommonLib?)
[02:27:19 ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.internal.CommonPlugin.handleReflectionMissing(CommonPlugin.java:92)
[02:27:19 ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.reflection.SafeField.load(SafeField.java:80)
[02:27:19 ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.reflection.SafeField.<init>(SafeField.java:59)
[02:27:19 ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.reflection.ClassTemplate.getField(ClassTemplate.java:253)
[02:27:19 ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.protocol.PacketTypeClasses$NMSPacketPlayInWindowClick.<init>(PacketTypeClasses.java:902)
[02:27:19 ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.protocol.PacketType.<clinit>(PacketType.java:137)
[02:27:19 ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.reflection.classes.EntityTrackerRef.<clinit>(EntityTrackerRef.java:25)
[02:27:19 ERROR]: [BKCommonLib] at java.lang.Class.forName0(Native Method)
[02:27:19 ERROR]: [BKCommonLib] at java.lang.Class.forName(Class.java:264)
[02:27:19 ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.Common.loadClasses(Common.java:118)
[02:27:19 ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.internal.CommonClasses.loadCommon(CommonClasses.java:61)
[02:27:19 ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.internal.CommonClasses.loadRef(CommonClasses.java:47)
[02:27:19 ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.internal.CommonClasses.init(CommonClasses.java:21)
[02:27:19 ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.internal.CommonPlugin.onLoad(CommonPlugin.java:308)
[02:27:19 ERROR]: [BKCommonLib] at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugins(CraftServer.java:301)
[02:27:19 ERROR]: [BKCommonLib] at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:201)
[02:27:19 ERROR]: [BKCommonLib] at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527)
[02:27:19 ERROR]: [BKCommonLib] at java.lang.Thread.run(Thread.java:745)
[02:27:19 WARN]: [BKCommonLib] Method void a(SoundEffect, BlockPosition) is not overrided in the World Listener!
[02:27:19 WARN]: [BKCommonLib] Method void a(World, BlockPosition, IBlockData, IBlockData, int) is not overrided in the World Listener!
[02:27:19 WARN]: [BKCommonLib] Entity Type 'LINGERING_POTION' is not registered as CommonEntityType

#### Expected behaviour:
No errors

#### Steps to reproduce:

Install Spigot.  Install BkCommonLib.  ???  Reproduced.

**Comment by FriwiDev** [comment]
Are you sure you are using the current BKCommonLib version? This bug was fixed 2 days ago.

**Comment by Catreina** [comment]
I have seen no update notice, nor any change in the download available from Spigot, so no, I am not sure.

**Comment by Catreina** [comment]
Got the update, installed and fixed.

Sorry for the bug report of an already fixed bug.
