### ISSUE TITLE
Field f does not exist in class file

### ISSUE THREAD

**Issue by Driphosting** [bergerhealer/BKCommonLib#23]
##### Spigot version: 1.9

<hr>

#### Problem or bug:

[11:49:51] [Server thread/INFO]: [BKCommonLib] Loading BKCommonLib v1.70-SNAPSHOT
[11:49:51] [Server thread/ERROR]: [BKCommonLib] [Reflection] Field 'f' does not exist in class file net.minecraft.server.v1_9_R1.PacketPlayInWindowClick (Update BKCommonLib?)
[11:49:51] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.internal.CommonPlugin.handleReflectionMissing(CommonPlugin.java:92)
[11:49:51] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.reflection.SafeField.load(SafeField.java:80)
[11:49:51] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.reflection.SafeField.<init>(SafeField.java:59)
[11:49:51] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.reflection.ClassTemplate.getField(ClassTemplate.java:253)
[11:49:51] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.protocol.PacketTypeClasses$NMSPacketPlayInWindowClick.<init>(PacketTypeClasses.java:902)
[11:49:51] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.protocol.PacketType.<clinit>(PacketType.java:137)
[11:49:51] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.reflection.classes.EntityTrackerRef.<clinit>(EntityTrackerRef.java:25)
[11:49:51] [Server thread/ERROR]: [BKCommonLib] at java.lang.Class.forName0(Native Method)
[11:49:51] [Server thread/ERROR]: [BKCommonLib] at java.lang.Class.forName(Unknown Source)
[11:49:51] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.Common.loadClasses(Common.java:118)
[11:49:51] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.internal.CommonClasses.loadCommon(CommonClasses.java:61)
[11:49:51] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.internal.CommonClasses.loadRef(CommonClasses.java:47)
[11:49:51] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.internal.CommonClasses.init(CommonClasses.java:21)
[11:49:51] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.internal.CommonPlugin.onLoad(CommonPlugin.java:308)
[11:49:51] [Server thread/ERROR]: [BKCommonLib] at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugins(CraftServer.java:301)
[11:49:51] [Server thread/ERROR]: [BKCommonLib] at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:201)
[11:49:51] [Server thread/ERROR]: [BKCommonLib] at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527)
[11:49:51] [Server thread/ERROR]: [BKCommonLib] at java.lang.Thread.run(Unknown Source)
[11:49:51] [Server thread/WARN]: [BKCommonLib] Method void a(SoundEffect, BlockPosition) is not overrided in the World Listener!
[11:49:51] [Server thread/WARN]: [BKCommonLib] Method void a(World, BlockPosition, IBlockData, IBlockData, int) is not overrided in the World Listener!
[11:49:51] [Server thread/INFO]: [BKCommonLib] Enabling BKCommonLib v1.70-SNAPSHOT
[11:49:51] [Server thread/INFO]: [BKCommonLib] BKCommonLib is running on Spigot (git-Spigot-b1c1b55-7d73fbb) : v1_9_R1 (Minecraft 1.9)
[11:49:51] [Server thread/INFO]: [BKCommonLib] [Network] Now using a PlayerConnection hook to provide Packet Listener and Monitor support
[11:49:51] [Server thread/INFO]: [BKCommonLib] Updating is like reinventing the wheel for BKCommonLib.
[11:49:51] [Server thread/INFO]: BKCommonLib version 1.70-SNAPSHOT enabled! (0.061s)

**Comment by FriwiDev** [comment]
Already fixed in 1.75

**Comment by Driphosting** [comment]
where is 1.75????

**Comment by FriwiDev** [comment]
as our builderver isnt working, its a build it yourself

**Comment by Driphosting** [comment]
Okay, the source here is 1.75?. 

Thanks for your time by the way!
I appriciate what you guys are doing for us!!!!

**Comment by Driphosting** [comment]
i cant make it working because of objenesis.
after re-importing all mavens it's giving me a few errors bacK:
http://pastebin.com/PbRsGDLR

**Comment by FriwiDev** [comment]
Wrong spigot version?

**Comment by mg-1999** [comment]
No it isn't a wrong version. It is an issue with the code he is compiling.
Which branch are you trying to build?

Op za 14 mei 2016 09:48 schreef Friwi <notifications@github.com>:

> Wrong spigot version?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bergerhealer/BKCommonLib/issues/23#issuecomment-219206660>
>
-- 

Met vriendelijk groeten,

Matthijs Giezenberg

**Comment by Driphosting** [comment]
Hey matthijs and friwi:)
First of all i'm also dutch :P

But you mean the language level? its 7
Library is fully maven + the added lib from the project so can't be the wrong version.
Using java 1.8.0_71
Intelij 15.0.3

Greets,
Joris

**Comment by mg-1999** [comment]
I mean which branch from git are you trying to build? Master of develop-1.9?

**Comment by Driphosting** [comment]
It's Master because i need the fixed patch #19 and the one on drone.io is outdated i guess because that isn't fixing the #19 error.

**Comment by Driphosting** [comment]
Found the problem. there is a spigot and craftbukkit version in the lib....

**Comment by Driphosting** [comment]
problem #19 still not fixed

**Comment by mg-1999** [comment]
It is fixed in the `developer-1.9` branch, you should pull that one and build local.
