### ISSUE TITLE
Error on server reload

### ISSUE THREAD

**Issue by RikoDEV** [bergerhealer/BKCommonLib#39]
##### Spigot version: git-Paper-1178 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

<hr>

#### Problem or bug:
Problem
#### Expected behaviour:
Reload the plugin.

#### Steps to reproduce:
1. Install BKCommonLib and MyWorlds
2. Remove Multiverse-Core
3. Reload server
4. 
```[18:29:03] [Server thread/INFO]: [My_Worlds] Enabling My_Worlds v1.12-v2
[18:29:05] [Server thread/ERROR]: [My_Worlds] An error occurred while enabling, the plugin will be disabled:
[18:29:05] [Server thread/ERROR]: [BKCommonLib] com.bergerkiller.mountiplex.dep.net.sf.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.dep.net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:237)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.dep.net.sf.cglib.proxy.Enhancer.createHelper(Enhancer.java:377)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.dep.net.sf.cglib.proxy.Enhancer.createClass(Enhancer.java:317)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.ClassInterceptor.createEnhancedClass(ClassInterceptor.java:390)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.ClassInterceptor.hook(ClassInterceptor.java:108)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.internal.hooks.PlayerFileDataHook.update(PlayerFileDataHook.java:27)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.controller.PlayerDataController.assign(PlayerDataController.java:46)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.mw.MyWorlds.enable(MyWorlds.java:170)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:783)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:795)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.Bukkit.reload(Bukkit.java:542)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:53)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:672)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1425)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1230)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at java.lang.Thread.run(Thread.java:748)
[18:29:05] [Server thread/ERROR]: [BKCommonLib] Caused by: java.lang.reflect.InvocationTargetException
[18:29:05] [Server thread/ERROR]: [BKCommonLib] java.lang.reflect.InvocationTargetException
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at java.lang.reflect.Method.invoke(Method.java:498)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.dep.net.sf.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:384)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.dep.net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:219)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.dep.net.sf.cglib.proxy.Enhancer.createHelper(Enhancer.java:377)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.dep.net.sf.cglib.proxy.Enhancer.createClass(Enhancer.java:317)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.ClassInterceptor.createEnhancedClass(ClassInterceptor.java:390)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.ClassInterceptor.hook(ClassInterceptor.java:108)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.internal.hooks.PlayerFileDataHook.update(PlayerFileDataHook.java:27)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.controller.PlayerDataController.assign(PlayerDataController.java:46)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.mw.MyWorlds.enable(MyWorlds.java:170)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:783)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:795)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.Bukkit.reload(Bukkit.java:542)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:53)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:672)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1425)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1230)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at java.lang.Thread.run(Thread.java:748)
[18:29:05] [Server thread/ERROR]: [BKCommonLib] Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_12_R1/ServerNBTManager$$EnhancerByCGLIB$$e8de4199
[18:29:05] [Server thread/ERROR]: [BKCommonLib] java.lang.NoClassDefFoundError: net/minecraft/server/v1_12_R1/ServerNBTManager$$EnhancerByCGLIB$$e8de4199
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at java.lang.ClassLoader.defineClass1(Native Method)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at java.lang.reflect.Method.invoke(Method.java:498)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.dep.net.sf.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:384)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.dep.net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:219)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.dep.net.sf.cglib.proxy.Enhancer.createHelper(Enhancer.java:377)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.dep.net.sf.cglib.proxy.Enhancer.createClass(Enhancer.java:317)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.ClassInterceptor.createEnhancedClass(ClassInterceptor.java:390)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.ClassInterceptor.hook(ClassInterceptor.java:108)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.internal.hooks.PlayerFileDataHook.update(PlayerFileDataHook.java:27)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.controller.PlayerDataController.assign(PlayerDataController.java:46)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.mw.MyWorlds.enable(MyWorlds.java:170)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:783)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:795)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.Bukkit.reload(Bukkit.java:542)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:53)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:672)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1425)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1230)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at java.lang.Thread.run(Thread.java:748)
[18:29:05] [Server thread/ERROR]: [BKCommonLib] Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_12_R1.ServerNBTManager$$EnhancerByCGLIB$$e8de4199
[18:29:05] [Server thread/ERROR]: [BKCommonLib] java.lang.ClassNotFoundException: net.minecraft.server.v1_12_R1.ServerNBTManager$$EnhancerByCGLIB$$e8de4199
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at java.lang.ClassLoader.defineClass1(Native Method)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at java.lang.reflect.Method.invoke(Method.java:498)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.dep.net.sf.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:384)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.dep.net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:219)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.dep.net.sf.cglib.proxy.Enhancer.createHelper(Enhancer.java:377)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.dep.net.sf.cglib.proxy.Enhancer.createClass(Enhancer.java:317)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.ClassInterceptor.createEnhancedClass(ClassInterceptor.java:390)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.ClassInterceptor.hook(ClassInterceptor.java:108)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.internal.hooks.PlayerFileDataHook.update(PlayerFileDataHook.java:27)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.controller.PlayerDataController.assign(PlayerDataController.java:46)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.mw.MyWorlds.enable(MyWorlds.java:170)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:783)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:795)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.Bukkit.reload(Bukkit.java:542)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:53)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:672)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1425)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1230)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[18:29:05] [Server thread/ERROR]: [BKCommonLib]   at java.lang.Thread.run(Thread.java:748)
[18:29:05] [Server thread/INFO]: [My_Worlds] Disabling My_Worlds v1.12-v2
[18:29:05] [Server thread/INFO]: [BKCommonLib] My_Worlds disabled!
```

**Comment by bergerkiller** [comment]
MyWorlds replaces the player data manager on the server to handle the loading/saving of player data. It has to keep this class hooked in the server after the plugin disables to make sure player data is correctly saved on server shutdown. This caused some problems with /reload, because it ended up re-hooking causing this error.

A bug thats a bit difficult to fix, unfortunately.
