### ISSUE TITLE
UnsupportedOperationException: Field net.minecraft.server.World.entityList is not available

### ISSUE THREAD

**Issue by mibby** [bergerhealer/BKCommonLib#61]
Paper dev 608 (Spigot 1.13.2)
BKCommonLib dev 531
LightCleaner dev 50

@bergerkiller RE: https://github.com/PaperMC/Paper/commit/5c0133110bde8092dac394ffc937618c0557c49b
https://github.com/PaperMC/Paper/commit/9dc4d6448bccc1989bf0f8bd0c0091df3fe9b909

```
[02:56:11] [Server thread/INFO]: [BKCommonLib] Loading BKCommonLib v1.13.2-v3-SNAPSHOT
[02:56:12] [Server thread/WARN]: [REFLECTION] A class member of net.minecraft.server.v1_13_R2.World was not found!
[02:56:12] [Server thread/WARN]: [REFLECTION] Failed to find field public final (List<EntityHandle>) com.destroystokyo.paper.PaperWorldEntityList entityList; - Alternatives:
[02:56:12] [Server thread/WARN]: [REFLECTION]   - public ArrayList<org.bukkit.craftbukkit.v1_13_R2.block.CraftBlockState> capturedBlockStates;
[02:56:12] [Server thread/WARN]: [REFLECTION]   - public final List<Entity> entityList;
[02:56:12] [Server thread/WARN]: [REFLECTION]   - public boolean guardEntityList;
[02:56:12] [Server thread/WARN]: [REFLECTION]   - public final List<TileEntity> tileEntityListTick;
[02:56:12] [Server thread/WARN]: [REFLECTION]   - private org.spigotmc.TickLimiter entityLimiter;
[02:56:12] [Server thread/WARN]: [REFLECTION]   - public boolean captureBlockStates;
[02:56:12] [Server thread/WARN]: [REFLECTION]   - public final co.aikar.timings.WorldTimingsHandler timings;
[02:56:12] [Server thread/WARN]: [REFLECTION]   - public final boolean isClientSide;
[02:56:13] [Server thread/WARN]: [REFLECTION] Field 'entityList' not found in template for net.minecraft.server.v1_13_R2.World
```

```
[02:56:19] [Server thread/ERROR]: Could not pass event WorldLoadEvent to BKCommonLib v1.13.2-v3-SNAPSHOT
java.lang.UnsupportedOperationException: Field net.minecraft.server.World.entityList is not available
	at com.bergerkiller.mountiplex.reflection.util.FastField.checkInit(FastField.java:59) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.util.FastField$FastFieldInitProxy.read(FastField.java:213) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.util.FastField$FastFieldInitProxy.get(FastField.java:279) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.util.FastField.get(FastField.java:167) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.declarations.Template$Field.get(Template.java:2159) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonMapController.iterateItemFrames(CommonMapController.java:1767) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonMapController.onWorldLoad(CommonMapController.java:695) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.13.2.jar:git-Paper-608]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-608]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-608]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-608]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546) ~[patched_1.13.2.jar:git-Paper-608]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-608]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-608]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-608]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
```
[02:56:27] [Server thread/ERROR]: Could not pass event WorldLoadEvent to BKCommonLib v1.13.2-v3-SNAPSHOT
java.lang.UnsupportedOperationException: Field net.minecraft.server.World.entityList is not available
	at com.bergerkiller.mountiplex.reflection.util.FastField.checkInit(FastField.java:59) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.util.FastField$FastFieldInitProxy.read(FastField.java:213) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.util.FastField$FastFieldInitProxy.get(FastField.java:279) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.util.FastField.get(FastField.java:167) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.declarations.Template$Field.get(Template.java:2159) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonMapController.iterateItemFrames(CommonMapController.java:1767) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonMapController.onWorldLoad(CommonMapController.java:695) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.13.2.jar:git-Paper-608]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-608]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-608]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-608]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.createWorld(CraftServer.java:1065) ~[patched_1.13.2.jar:git-Paper-608]
	at org.bukkit.Bukkit.createWorld(Bukkit.java:520) ~[patched_1.13.2.jar:git-Paper-608]
	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:279) ~[patched_1.13.2.jar:git-Paper-608]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:448) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:423) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:728) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:310) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-608]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-608]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-608]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-608]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-608]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-608]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-608]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-608]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-608]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-608]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
```
[02:56:39] [Server thread/WARN]: [BKCommonLib] Task #15 for BKCommonLib v1.13.2-v3-SNAPSHOT generated an exception
java.lang.UnsupportedOperationException: Field net.minecraft.server.World.entityList is not available
	at com.bergerkiller.mountiplex.reflection.util.FastField.checkInit(FastField.java:59) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.util.FastField$FastFieldInitProxy.read(FastField.java:213) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.util.FastField$FastFieldInitProxy.get(FastField.java:279) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.util.FastField.get(FastField.java:167) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.declarations.Template$Field.get(Template.java:2159) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonMapController.iterateItemFrames(CommonMapController.java:1767) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonMapController.findNeighbours(CommonMapController.java:1703) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonMapController.access$000(CommonMapController.java:88) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonMapController$ItemFrameInfo.recalculateUUID(CommonMapController.java:1219) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonMapController$ItemFrameInfo.updateItem(CommonMapController.java:1208) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonMapController$FramedMapUpdater.run(CommonMapController.java:1449) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-608]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-608]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.2.jar:git-Paper-608]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-608]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-608]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-608]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by bergerkiller** [comment]
Oh, did paper devs revert their changes with the entity list again? Bah. I'll make a quick tweak.

**Comment by bergerkiller** [comment]
See if this fixes it https://github.com/bergerhealer/BKCommonLib/commit/4cd5718395169ba9478b73571199fca3ee5fd230

https://ci.mg-dev.eu/job/BKCommonLib/532/

**Comment by mibby** [comment]
Seems to have fixed it, thanks!
