### ISSUE TITLE
Random error on cancelled logins

### ISSUE THREAD

**Issue by TheDGOfficial** [bergerhealer/BKCommonLib#72]
##### Spigot version: Paper 1.13.2, build 639

<hr>

#### Problem or bug:

This random error occurs on cancelled logins:

```
[08:41:39 ERROR]: Could not pass event PlayerJoinEvent to BKCommonLib v1.13.2-v3
java.util.NoSuchElementException: packet_handler
        at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1119) ~[patched_1.13.2.jar:git-Paper-639]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:260) ~[patched_1.13.2.jar:git-Paper-639]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:249) ~[patched_1.13.2.jar:git-Paper-639]
        at com.bergerkiller.bukkit.common.internal.network.CommonPacketHandler$CommonChannelListener.bind(CommonPacketHandler.java:91) ~[?:?]
        at com.bergerkiller.bukkit.common.internal.network.CommonPacketHandler.onPlayerJoin(CommonPacketHandler.java:70) ~[?:?]
        at com.bergerkiller.bukkit.common.internal.CommonListener.onPlayerJoin(CommonListener.java:99) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.13.2.jar:git-Paper-639]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.13.2.jar:git-Paper-639]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-639]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-639]
        at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:369) ~[patched_1.13.2.jar:git-Paper-639]
        at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:180) ~[patched_1.13.2.jar:git-Paper-639]
        at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:169) ~[patched_1.13.2.jar:git-Paper-639]
        at net.minecraft.server.v1_13_R2.LoginListener.tick(LoginListener.java:65) ~[patched_1.13.2.jar:git-Paper-639]
        at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:271) ~[patched_1.13.2.jar:git-Paper-639]
        at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:129) ~[patched_1.13.2.jar:git-Paper-639]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1132) ~[patched_1.13.2.jar:git-Paper-639]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-639]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-639]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-639]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

#### Expected behaviour:

Expected no errors.

#### Steps to reproduce:

It's a random error but it occurs when logging in and cancelling it. It does not occur on every cancelled login, it's random.

**Comment by TheDGOfficial** [comment]
Oh, i see the commit https://github.com/bergerhealer/BKCommonLib/commit/de48ee5be9cc1493d53f3fff649a39e52ddf1431
It should fix this error. I'm closing the issue, sorry.
