### ISSUE TITLE
Stack Trace on load world (startup) using generator EpicWorldGenerator (does not happen without BKCommonLib)

### ISSUE THREAD

**Issue by bbayu123** [bergerhealer/BKCommonLib#75]
##### Spigot version: b1571

Other Plugins:
EpicWorldGenerator (PREMIUM) 8.0.0-SNAPSHOT-4
Multiverse-Core 2.6.0-SNAPSHOT-b737

<hr>

#### Problem or bug:
Stack Trace on load world using generator EpicWorldGenerator
I know it shows Multiverse somewhere here, but it also gives that for the default world, which is not loaded with Multiverse.

```
[20:01:45 INFO]: Preparing start region for level 8 (Seed: -363599993772883793)
[20:01:45 INFO]: -------- World Settings For [Kingdom02] --------
[20:01:45 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[20:01:45 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[20:01:45 INFO]: Item Merge Radius: 2.5
[20:01:45 INFO]: Item Despawn Rate: 6000
[20:01:45 INFO]: Arrow Despawn Rate: 1200
[20:01:45 INFO]: View Distance: 10
[20:01:45 INFO]: Zombie Aggressive Towards Villager: true
[20:01:45 INFO]: Experience Merge Radius: 3.0
[20:01:45 INFO]: Nerfing mobs spawned from spawners: false
[20:01:45 INFO]: Mob Spawn Range: 4
[20:01:45 INFO]: Cactus Growth Modifier: 100%
[20:01:45 INFO]: Cane Growth Modifier: 100%
[20:01:45 INFO]: Melon Growth Modifier: 100%
[20:01:45 INFO]: Mushroom Growth Modifier: 100%
[20:01:45 INFO]: Pumpkin Growth Modifier: 100%
[20:01:45 INFO]: Sapling Growth Modifier: 100%
[20:01:45 INFO]: Wheat Growth Modifier: 100%
[20:01:45 INFO]: NetherWart Growth Modifier: 100%
[20:01:45 INFO]: Vine Growth Modifier: 100%
[20:01:45 INFO]: Cocoa Growth Modifier: 100%
[20:01:45 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[20:01:45 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[20:01:45 INFO]: Random Lighting Updates: false
[20:01:45 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[20:01:45 INFO]: Max TNT Explosions: 100
[20:01:45 INFO]: Structure Info Saving: true
[20:01:45 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[20:01:45 INFO]: CUSTOM TERRAIN: Scots pine forest
[20:01:45 INFO]: ~~~~~~~~~~~~[ EWG Settings for Kingdom02 ]~~~~~~~~~~~~
[20:01:45 INFO]: Biomes that will generated;
[20:01:45 INFO]:  * Mesa
[20:01:45 INFO]:  * Farmland
[20:01:45 INFO]:  * Tropical Forest
[20:01:45 INFO]:  * Volcano
[20:01:45 INFO]:  * Deciduous Forest
[20:01:45 INFO]:  * River
[20:01:45 INFO]:  * Deep Ocean
[20:01:45 INFO]:  * Birch Forest
[20:01:45 INFO]:  * Fantasy Forest
[20:01:45 INFO]:  * Bonsai Forest
[20:01:45 INFO]:  * Pine Forest
[20:01:45 INFO]:  * Plains
[20:01:45 INFO]:  * Bonsai Forest
[20:01:45 INFO]:  * Jungle
[20:01:45 INFO]:  * Desert
[20:01:45 INFO]:  * Ocean
[20:01:45 INFO]:  * Forgotten Forest
[20:01:45 INFO]:  * Stone Forest
[20:01:45 INFO]:  * Scots pine forest
[20:01:45 INFO]:  * Swamp
[20:01:45 INFO]:  * Swamp Edge
[20:01:45 INFO]:  * Snowy Pine
[20:01:45 INFO]:  * Mega Taiga
[20:01:45 INFO]:  * Mega Spruce Taiga
[20:01:45 INFO]:  * Savanna
[20:01:45 INFO]:  * Swampland
[20:01:45 INFO]: Generator version: 7.2.24
[20:01:45 INFO]: Biomes in total: 26
[20:01:45 INFO]: Preparing world injection
[20:01:45 WARN]: java.lang.IllegalArgumentException: Cannot subclass final class minelazz.iIiIIiIIII
[20:01:45 WARN]:        at com.bergerkiller.mountiplex.dep.net.sf.cglib.proxy.Enhancer.generateClass(Enhancer.java:565)
[20:01:45 WARN]:        at com.bergerkiller.mountiplex.dep.net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
[20:01:45 WARN]:        at com.bergerkiller.mountiplex.dep.net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:329)
[20:01:45 WARN]:        at com.bergerkiller.mountiplex.dep.net.sf.cglib.proxy.Enhancer.generate(Enhancer.java:492)
[20:01:45 WARN]:        at com.bergerkiller.mountiplex.dep.net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
[20:01:45 WARN]:        at com.bergerkiller.mountiplex.dep.net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
[20:01:45 WARN]:        at com.bergerkiller.mountiplex.dep.net.sf.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
[20:01:45 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[20:01:45 WARN]:        at com.bergerkiller.mountiplex.dep.net.sf.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
[20:01:45 WARN]:        at com.bergerkiller.mountiplex.dep.net.sf.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
[20:01:45 WARN]:        at com.bergerkiller.mountiplex.dep.net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
[20:01:45 WARN]:        at com.bergerkiller.mountiplex.dep.net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291)
[20:01:45 WARN]:        at com.bergerkiller.mountiplex.dep.net.sf.cglib.proxy.Enhancer.createHelper(Enhancer.java:480)
[20:01:45 WARN]:        at com.bergerkiller.mountiplex.dep.net.sf.cglib.proxy.Enhancer.createClass(Enhancer.java:337)
[20:01:45 WARN]:        at com.bergerkiller.mountiplex.reflection.ClassInterceptor.createEnhancedClass(ClassInterceptor.java:418)
[20:01:45 WARN]:        at com.bergerkiller.mountiplex.reflection.ClassInterceptor.hook(ClassInterceptor.java:119)
[20:01:45 WARN]:        at com.bergerkiller.bukkit.common.internal.hooks.ChunkGeneratorHook.hook(ChunkGeneratorHook.java:45)
[20:01:45 WARN]:        at com.bergerkiller.bukkit.common.internal.CommonListener.onWorldInit(CommonListener.java:56)
[20:01:45 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:01:45 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20:01:45 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:01:45 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[20:01:45 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[20:01:45 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[20:01:45 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[20:01:45 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[20:01:45 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.createWorld(CraftServer.java:922)
[20:01:45 WARN]:        at org.bukkit.Bukkit.createWorld(Bukkit.java:454)
[20:01:45 WARN]:        at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
[20:01:45 WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:466)
[20:01:45 WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:447)
[20:01:45 WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:422)
[20:01:45 WARN]:        at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:725)
[20:01:45 WARN]:        at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:312)
[20:01:45 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[20:01:45 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[20:01:45 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[20:01:45 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[20:01:45 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
[20:01:45 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[20:01:45 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[20:01:45 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[20:01:45 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[20:01:45 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[20:01:45 WARN]:        at java.lang.Thread.run(Unknown Source)
```

**Comment by bergerkiller** [comment]
Problem is obvious, it cannot extend a final class that is from another plugin. The only reason it wants to do this, is to override getMobsFor and control mob spawning this way with minimal overhead. This is only used by MyWorlds to restrict what mobs are allowed to spawn.

I assume you're not using MyWorlds, so probably the easiest solution is to not perform this hooking when the BKCommonLib 'CreaturePreSpawnEvent' has no handlers.

**Comment by bergerkiller** [comment]
https://github.com/bergerhealer/BKCommonLib/commit/692dc28635ed106aa64219d04691bec6271ce901
https://github.com/bergerhealer/BKCommonLib/commit/9845124f06cc54d63ba5cf44d0c3c597729ab6ae

These two should fix this issue. The getMobsFor is not essential, its just a performance tweak to reduce the number of creature spawn events that are handled. If it doesn't work for a custom-gen world, it won't cause MyWorlds creature spawn disabling to fail.

**Comment by bbayu123** [comment]
Great! It's fixed!
