### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by Vlader97** [bergerhealer/BKCommonLib#76]
##### Paper version: 1.14.4 B171

<hr>

#### Problem or bug:
This error shows randomly I don't know what cause it.
```
[11:08:12] [Netty Epoll Server IO #2/ERROR]: [BKCommonLib.Network] [BKCommonLib] [Network] Error occurred in onPacketSend handling PacketPlayOutEntityMetadata:
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_212]
	at java.util.HashMap$ValueIterator.next(HashMap.java:1474) ~[?:1.8.0_212]
	at com.bergerkiller.bukkit.common.internal.CommonMapController.iterateItemFrames(CommonMapController.java:1908) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonMapController.findNeighbours(CommonMapController.java:1790) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonMapController.access$000(CommonMapController.java:89) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonMapController$ItemFrameInfo.recalculateUUID(CommonMapController.java:1243) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonMapController$ItemFrameInfo.updateItem(CommonMapController.java:1232) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonMapController.onPacketSend(CommonMapController.java:543) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.network.PacketHandlerHooked.handlePacketSend(PacketHandlerHooked.java:304) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.network.CommonPacketHandler$CommonChannelListener.write(CommonPacketHandler.java:127) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[patched_1.14.4.jar:git-Paper-171]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[patched_1.14.4.jar:git-Paper-171]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[patched_1.14.4.jar:git-Paper-171]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[patched_1.14.4.jar:git-Paper-171]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[patched_1.14.4.jar:git-Paper-171]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) ~[patched_1.14.4.jar:git-Paper-171]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[patched_1.14.4.jar:git-Paper-171]
	at net.minecraft.server.v1_14_R1.NetworkManager.lambda$b$4(NetworkManager.java:205) ~[patched_1.14.4.jar:git-Paper-171]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[patched_1.14.4.jar:git-Paper-171]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[patched_1.14.4.jar:git-Paper-171]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313) ~[patched_1.14.4.jar:git-Paper-171]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.14.4.jar:git-Paper-171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```
#### Expected behaviour:
Not show error.

**Comment by bbayu123** [comment]
Remove ProtocolLib and ProtocolSupport if you have those, also list all the plugins that depend on BKCommonLib in which you are using for diagnoses purposes.

**Comment by Vlader97** [comment]
I do not have ProtocolLib and ProtocolSupport on the server.
I have only Traincarts plugin that depends on BkCommonLib.

**Comment by bbayu123** [comment]
Ok then probably something wrong elsewhere then, berger will get back to you later.

**Comment by bergerkiller** [comment]
Asynchronous bug. Handlers occur on another thread and if some part of the code doesnt take that into account bad things can/will happen. I'll look into that now

**Comment by bergerkiller** [comment]
Don't know how often this particular error occurred. This should fix it. Hopefully no new bugs occur now that it caches the by-world item frames.

https://github.com/bergerhealer/BKCommonLib/commit/2589f029f1999962d76774ab2b2e89df557ce5ec

https://ci.mg-dev.eu/job/BKCommonLib/599/

**Comment by Vlader97** [comment]
I confirm that it is fixed. It's not showing anymore.
